import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  select: {
    fontFamily: 'Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif',
    display: 'block',
    width: '100%',
    margin: '0px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingRight: '28px',
    paddingLeft: '10px',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    textTransform: 'none',
    appearance: 'none',
    transition: 'border-color 0.2s',
    border: '1px solid #aaa',
    borderRadius: '2px',
    backgroundColor: '#fff',
    color: '#484848',
    lineHeight: 'normal',
  },
  selectBlock: {
    position: 'relative',
    display: 'inline-block',
    verticalAlign: 'bottom',
    ':before': {
      content: '"\\25bc"',
      position: 'absolute',
      pointerEvents: 'none',
      color: '#767676',
      top: '0px',
      bottom: '1px',
      paddingTop: '0.7em',
      lineHeight: 1,
      right: '0px',
      width: '2em',
      textAlign: 'center',
      transform: 'scale(0.84, 0.42)',
      filter: 'progid:DXImageTransform.Microsoft.Matrix(M11=0.84, M12=0, M21=0, M22=0.42, SizingMethod="auto expand")',
    },
  },
});
