const checkoutActionTypes = {
  SET_ACTIVE_STEP: 'zipcube/checkout/SET_ACTIVE_STEP',
  PROGRESS: 'zipcube/checkout/PROGRESS',
  SET_INITIAL_STEP: 'zipcube/checkout/SET_INITIAL_STEP',
  HANDLE_CHANGE: 'zipcube/checkout/HANDLE_CHANGE',
  IS_LOGGED_IN: 'zipcube/checkout/IS_LOGGED_IN',
  SET_INITIAL_USER: 'zipcube/checkout/SET_INITIAL_USER',
  SET_USER: 'zipcube/checkout/SET_USER',
  FORGOT_PASSWORD: 'zipcube/checkout/FORGOT_PASSWORD',
  HANDLE_FINISHING: 'zipcube/checkout/HANDLE_FINISHING',
  TOGGLE_FINISH_BUTTON: 'zipcube/checkout/TOGGLE_FINISH_BUTTON',
  SHOW_MAP_MODAL: 'zipcube/checkout/SHOW_MAP_MODAL',
  UNDO_FORGOT_PASSWORD: 'zipcube/checkout/UNDO_FORGOT_PASSWORD',
  SET_RESERVATION: 'zipcube/checkout/SET_RESERVATION',
  SET_DEFAULT_CONFIGURATION: 'zipcube/checkout/SET_DEFAULT_CONFIGURATION',
  HANDLE_PASSWORD_CHANGE: 'zipcube/checkout/HANDLE_PASSWORD_CHANGE',
  HANDLE_USER_INPUT_CHANGE: 'zipcube/checkout/HANDLE_USER_INPUT_CHANGE',
  HANDLE_USER_PHONE_INPUT_CHANGE: 'zipcube/checkout/HANDLE_USER_PHONE_INPUT_CHANGE',
  TOGGLE_FLEXIBLE: 'zipcube/checkout/TOGGLE_FLEXIBLE',
  HANDLE_VISITED: 'zipcube/checkout/HANDLE_VISITED',
  SKIP_SAVE_DETAILS: 'zipcube/checkout/SKIP_SAVE_DETAILS',
  CHECKOUT_AS_GUEST: 'zipcube/checkout/CHECKOUT_AS_GUEST',
  UNDO_CHECKOUT_AS_GUEST: 'zipcube/checkout/UNDO_CHECKOUT_AS_GUEST',
  SHOW_SIDEBAR_ON_MOBILE: 'zipcube/checkout/SHOW_SIDEBAR_ON_MOBILE',
  SET_INITIAL_BOOKING_REQUEST: 'zipcube/checkout/SET_INITIAL_BOOKING_REQUEST',
  SET_BOOKING_TOTAL: 'zipcube/checkout/SET_BOOKING_TOTAL',
  HANDLE_ADD_ON: 'zipcube/checkout/HANDLE_ADD_ON',
  HANDLE_ADMIN_OVERRIDE: 'zipcube/checkout/HANDLE_ADMIN_OVERRIDE',
  HANDLE_EXTRA_FEE: 'zipcube/checkout/HANDLE_EXTRA_FEE',
  HANDLE_SERVICE_RATING: 'zipcube/checkout/HANDLE_SERVICE_RATING',
  HANDLE_SERVICE_COMMENTS: 'zipcube/checkout/HANDLE_SERVICE_COMMENTS',
  LOGIN: 'zipcube/checkout/LOGIN',
  RESSET_PASSWORD_REQUEST: 'zipcube/checkout/RESSET_PASSWORD_REQUEST',

  SAVE_DETAILS_REQUEST: 'zipcube/checkout/SAVE_DETAILS_REQUEST',
  SAVE_DETAILS_SUCCESS: 'zipcube/checkout/SAVE_DETAILS_SUCCESS',
  SAVE_DETAILS_FAILURE: 'zipcube/checkout/SAVE_DETAILS_FAILURE',

  REVIEW_DATA_REQUEST: 'zipcube/checkout/REVIEW_DATA_REQUEST',
  REVIEW_DATA_SUCCESS: 'zipcube/checkout/REVIEW_DATA_SUCCESS',
  REVIEW_DATA_FAILURE: 'zipcube/checkout/REVIEW_DATA_FAILURE',


  ADD_OR_UPDATE_USER_REQUEST: 'zipcube/checkout/ADD_OR_UPDATE_USER_REQUEST',
  ADD_OR_UPDATE_USER_SUCCESS: 'zipcube/checkout/ADD_OR_UPDATE_USER_SUCCESS',
  ADD_OR_UPDATE_USER_FAILURE: 'zipcube/checkout/ADD_OR_UPDATE_USER_FAILURE',

  SAVE_BOOKING_REQUEST: 'zipcube/checkout/SAVE_BOOKING_REQUEST',
  SAVE_BOOKING_SUCCESS: 'zipcube/checkout/SAVE_BOOKING_SUCCESS',
  SAVE_BOOKING_FAILURE: 'zipcube/checkout/SAVE_BOOKING_FAILURE'
};

export default checkoutActionTypes;

