import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  navContainer: {
    display: 'none',
    opacity: 1,
    webkitTransition: '0.25s opacity ease-out',
    mozTransition: '0.25s opacity ease-out',
    transition: '0.25s opacity ease-out',
    '@media (min-width: 1025px)': {
      display: 'block',
    },
  },
  navList: {
    display: 'table',
    listStyle: 'none',
    height: '64px',
  },
  navLink: {
    webkitAppearance: 'none',
    mozAppearance: 'none',
    appearance: 'none',
    background: 'transparent',
    border: '0px none',
    color: '#484848',
    display: 'inline-block',
    height: '64px',
    fontSize: '15px',
    fontWeight: 600,
    lineHeight: '64px',
    textDecoration: 'none',
    margin: '0px',
    position: 'relative',
    padding: '0px 8px',
    whiteSpace: 'nowrap',
    outline: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    '@media (min-width: 744px)': {
      height: '80px',
      lineHeight: '80px',
    },
  },
  notificationBadge: {
    fill: '#00c6ff',
    height: '6px',
    opacity: 0,
    position: 'absolute',
    top: '50%',
    webkitTransform: 'translate3d(4px, -8px, 0)',
    msTransform: 'translate3d(4px, -8px, 0)',
    transform: 'translate3d(4px, -8px, 0)',
    webkitTransformOriginX: '7px',
    msTransformOriginX: '7px',
    transformOriginX: '7px',
    webkitTransformOriginY: '-5px',
    msTransformOriginY: '-5px',
    transformOriginY: '-5px',
    width: '6px',
  },
  newText: {
    fontStyle: 'italic',
    color: '#00c6ff',
  },
});
