import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  searchBarWrapper: {
    display: 'block',
    paddingTop: '32px',
    paddingBottom: '8px',
    '@media (max-width: 767px)': {
      paddingTop: '0px',
    },
  },
  searchBarInputsContainer: {
    fontSize: '19px',
    lineHeight: '24px',
    paddingTop: '0px',
    paddingBottom: '0px',
    color: '#484848',
    borderRadius: '4px',
    border: '1px solid #dbdbdb',
    boxShadow: '0px 1px 3px 0px rgba(0, 0, 0, 0.08)',
    padding: '0px',
    display: 'table',
    tableLayout: 'fixed',
    width: '100%',
    position: 'relative',
    ':before': {
      content: '" "',
      display: 'table',
    },
    '@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : portrait)': {
      tableLayout: 'auto',
    },
    '@media (max-width: 767px)': {
      display: 'block',
    },
  },
  searchBarInputContainer: {
    position: 'relative',
    transition: 'width 0.3s',
    width: '100%',
    '@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : portrait)': {
      width: '27%',
    },
    '@media (max-width: 767px)': {
      display: 'block',
      width: '100%',
      borderBottom: '1px solid #e4e4e4',
      ':last-child': {
        borderBottom: '0px',
      },
    },
  },
  searchBarInputContainer_borderLeft: {
    position: 'relative',
    transition: 'width 0.3s',
    width: '100%',
    borderLeft: '1px solid #e4e4e4',
    '@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : portrait)': {
      width: '27%',
    },
    '@media (max-width: 767px)': {
      display: 'block',
      borderLeft: '0px',
      borderRight: '0px',
      borderBottom: '1px solid #e4e4e4',
    },
  },
  searchBarInputContainer_borderLeftRight: {
    position: 'relative',
    transition: 'width 0.3s',
    width: '100%',
    borderLeft: '1px solid #e4e4e4',
    borderRight: '1px solid #e4e4e4',
    '@media only screen and (min-device-width : 768px) and (max-device-width : 1024px) and (orientation : portrait)': {
      width: '27%',
    },
    '@media (max-width: 767px)': {
      display: 'block',
      borderLeft: '0px',
      borderRight: '0px',
      borderBottom: '1px solid #e4e4e4',
    },
  },
  searchBarInputContainer_borderless: {
    fontSize: '19px',
    lineHeight: '24px',
    color: '#484848',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#ffffff',
    borderRadius: '2px',
    backgroundColor: '#ffffff',
    marginBottom: '0px',
    zIndex: 0,
    marginTop: '0px',
    marginLeft: '0px',
    marginRight: '0px',
    display: 'block',
    width: '100%',
  },
  searchBarInputLabel: {
    fontSize: '15px',
    lineHeight: '18px',
    letterSpacing: '0.2px',
    paddingTop: '0px',
    paddingBottom: '0px',
    color: '#484848',
    display: 'block',
    marginLeft: '16px',
    marginTop: '16px',
  },
  searchBarBlockFullWidth: {
    display: 'block',
    width: '100%',
  },
  searchBarGeoInputContainer: {
    marginTop: '-3px',
    marginLeft: '5px',
  },
  visuallyHidden: {
    position: 'absolute',
    display: 'block',
    border: '0px none',
    margin: '-1px',
    padding: '0px',
    height: '1px',
    width: '1px',
    clip: 'rect(0px, 0px, 0px, 0px)',
    overflow: 'hidden',
  },
  searchBarFocusUnderline: {
    position: 'absolute',
    left: '0px',
    right: '0px',
    bottom: '0px',
    height: '2px',
    background: '#00c6ff',
    transition: 'opacity 0.3s',
    opacity: 0,
    zIndex: 1,
  },
  searchBarSearchButtonContainer: {
    width: '0%',
    '@media (max-width: 767px)': {
      width: '100%',
      textAlign: 'center',
    },
  },
  searchBarSearchButton: {
    fontFamily: 'Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif',
    fontSize: '19px',
    lineHeight: '15px',
    paddingTop: '0px',
    paddingBottom: '0px',
    color: '#ffffff',
    paddingLeft: '18px',
    paddingRight: '18px',
    borderRadius: '4px',
    border: '0px none',
    background: '#00c6ff',
    margin: '12px',
    marginLeft: '16px',
    height: '48px',
    textAlign: 'center',
    display: 'inline-block',
    cursor: 'pointer',
    float: 'right',
    '@media (max-width: 767px)': {
      float: 'none',
    },
  },
});
