<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string formattedAddress = 1;</code>
     */
    private $formattedAddress = '';
    /**
     * Generated from protobuf field <code>string streetNumber = 2;</code>
     */
    private $streetNumber = '';
    /**
     * Generated from protobuf field <code>string street = 3;</code>
     */
    private $street = '';
    /**
     * Generated from protobuf field <code>string country = 4;</code>
     */
    private $country = '';
    /**
     * Generated from protobuf field <code>string countryCode = 5;</code>
     */
    private $countryCode = '';
    /**
     * Generated from protobuf field <code>string city = 6;</code>
     */
    private $city = '';
    /**
     * Generated from protobuf field <code>string town = 7;</code>
     */
    private $town = '';
    /**
     * Generated from protobuf field <code>string county = 8;</code>
     */
    private $county = '';
    /**
     * Generated from protobuf field <code>string postcode = 9;</code>
     */
    private $postcode = '';
    /**
     * Generated from protobuf field <code>string extra = 10;</code>
     */
    private $extra = '';
    /**
     * Generated from protobuf field <code>string placeId = 11;</code>
     */
    private $placeId = '';
    /**
     * Generated from protobuf field <code>string autocomplete = 12;</code>
     */
    private $autocomplete = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $formattedAddress
     *     @type string $streetNumber
     *     @type string $street
     *     @type string $country
     *     @type string $countryCode
     *     @type string $city
     *     @type string $town
     *     @type string $county
     *     @type string $postcode
     *     @type string $extra
     *     @type string $placeId
     *     @type string $autocomplete
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string formattedAddress = 1;</code>
     * @return string
     */
    public function getFormattedAddress()
    {
        return $this->formattedAddress;
    }

    /**
     * Generated from protobuf field <code>string formattedAddress = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFormattedAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->formattedAddress = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string streetNumber = 2;</code>
     * @return string
     */
    public function getStreetNumber()
    {
        return $this->streetNumber;
    }

    /**
     * Generated from protobuf field <code>string streetNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStreetNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->streetNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string street = 3;</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Generated from protobuf field <code>string street = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 4;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string countryCode = 5;</code>
     * @return string
     */
    public function getCountryCode()
    {
        return $this->countryCode;
    }

    /**
     * Generated from protobuf field <code>string countryCode = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCountryCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->countryCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string town = 7;</code>
     * @return string
     */
    public function getTown()
    {
        return $this->town;
    }

    /**
     * Generated from protobuf field <code>string town = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTown($var)
    {
        GPBUtil::checkString($var, True);
        $this->town = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string county = 8;</code>
     * @return string
     */
    public function getCounty()
    {
        return $this->county;
    }

    /**
     * Generated from protobuf field <code>string county = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCounty($var)
    {
        GPBUtil::checkString($var, True);
        $this->county = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string postcode = 9;</code>
     * @return string
     */
    public function getPostcode()
    {
        return $this->postcode;
    }

    /**
     * Generated from protobuf field <code>string postcode = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPostcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string extra = 10;</code>
     * @return string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * Generated from protobuf field <code>string extra = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkString($var, True);
        $this->extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string placeId = 11;</code>
     * @return string
     */
    public function getPlaceId()
    {
        return $this->placeId;
    }

    /**
     * Generated from protobuf field <code>string placeId = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPlaceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->placeId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string autocomplete = 12;</code>
     * @return string
     */
    public function getAutocomplete()
    {
        return $this->autocomplete;
    }

    /**
     * Generated from protobuf field <code>string autocomplete = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setAutocomplete($var)
    {
        GPBUtil::checkString($var, True);
        $this->autocomplete = $var;

        return $this;
    }

}

