<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.AreaUnit</code>
 */
class AreaUnit
{
    /**
     * Generated from protobuf enum <code>NOAREAUNIT = 0;</code>
     */
    const NOAREAUNIT = 0;
    /**
     * Generated from protobuf enum <code>M2 = 1;</code>
     */
    const M2 = 1;
    /**
     * Generated from protobuf enum <code>FT2 = 2;</code>
     */
    const FT2 = 2;

    private static $valueToName = [
        self::NOAREAUNIT => 'NOAREAUNIT',
        self::M2 => 'M2',
        self::FT2 => 'FT2',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

