<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetIdMap</code>
 */
class AssetIdMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>.zipcube.Id humanRef = 2;</code>
     */
    private $humanRef = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $id
     *     @type \App\Types\Id $humanRef
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @return \App\Types\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id humanRef = 2;</code>
     * @return \App\Types\Id
     */
    public function getHumanRef()
    {
        return $this->humanRef;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id humanRef = 2;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setHumanRef($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->humanRef = $var;

        return $this;
    }

}

