<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetNesting</code>
 */
class AssetNesting extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     */
    private $assetId = null;
    /**
     * Generated from protobuf field <code>.zipcube.Container container = 2;</code>
     */
    private $container = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.Layout layouts = 3;</code>
     */
    private $layouts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $assetId
     *     @type \App\Types\Container $container
     *     @type \App\Types\Layout[]|\Google\Protobuf\Internal\RepeatedField $layouts
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @return \App\Types\Id
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->assetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Container container = 2;</code>
     * @return \App\Types\Container
     */
    public function getContainer()
    {
        return $this->container;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Container container = 2;</code>
     * @param \App\Types\Container $var
     * @return $this
     */
    public function setContainer($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Container::class);
        $this->container = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Layout layouts = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLayouts()
    {
        return $this->layouts;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Layout layouts = 3;</code>
     * @param \App\Types\Layout[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLayouts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\Layout::class);
        $this->layouts = $arr;

        return $this;
    }

}

