<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetConfiguration</code>
 */
class AssetConfiguration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Configuration kind = 1;</code>
     */
    private $kind = 0;
    /**
     * Generated from protobuf field <code>int32 maxPax = 2;</code>
     */
    private $maxPax = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *     @type int $maxPax
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Configuration kind = 1;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Configuration kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \App\Types\Configuration::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxPax = 2;</code>
     * @return int
     */
    public function getMaxPax()
    {
        return $this->maxPax;
    }

    /**
     * Generated from protobuf field <code>int32 maxPax = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPax($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxPax = $var;

        return $this;
    }

}

