<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.AssetStyle</code>
 */
class AssetStyle
{
    /**
     * Generated from protobuf enum <code>NOSTYLE = 0;</code>
     */
    const NOSTYLE = 0;
    /**
     * Generated from protobuf enum <code>QUIRKY = 1;</code>
     */
    const QUIRKY = 1;
    /**
     * Generated from protobuf enum <code>AFFORDABLE = 2;</code>
     */
    const AFFORDABLE = 2;
    /**
     * Generated from protobuf enum <code>CORPORATE = 3;</code>
     */
    const CORPORATE = 3;
    /**
     * Generated from protobuf enum <code>LUXURY = 4;</code>
     */
    const LUXURY = 4;

    private static $valueToName = [
        self::NOSTYLE => 'NOSTYLE',
        self::QUIRKY => 'QUIRKY',
        self::AFFORDABLE => 'AFFORDABLE',
        self::CORPORATE => 'CORPORATE',
        self::LUXURY => 'LUXURY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

