<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetPermissions</code>
 */
class AssetPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool canApprove = 1;</code>
     */
    private $canApprove = false;
    /**
     * Generated from protobuf field <code>bool canUpdate = 2;</code>
     */
    private $canUpdate = false;
    /**
     * Generated from protobuf field <code>bool canNest = 3;</code>
     */
    private $canNest = false;
    /**
     * Generated from protobuf field <code>bool getsNotified = 4;</code>
     */
    private $getsNotified = false;
    /**
     * Generated from protobuf field <code>bool canDelete = 5;</code>
     */
    private $canDelete = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $canApprove
     *     @type bool $canUpdate
     *     @type bool $canNest
     *     @type bool $getsNotified
     *     @type bool $canDelete
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool canApprove = 1;</code>
     * @return bool
     */
    public function getCanApprove()
    {
        return $this->canApprove;
    }

    /**
     * Generated from protobuf field <code>bool canApprove = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanApprove($var)
    {
        GPBUtil::checkBool($var);
        $this->canApprove = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool canUpdate = 2;</code>
     * @return bool
     */
    public function getCanUpdate()
    {
        return $this->canUpdate;
    }

    /**
     * Generated from protobuf field <code>bool canUpdate = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->canUpdate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool canNest = 3;</code>
     * @return bool
     */
    public function getCanNest()
    {
        return $this->canNest;
    }

    /**
     * Generated from protobuf field <code>bool canNest = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanNest($var)
    {
        GPBUtil::checkBool($var);
        $this->canNest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool getsNotified = 4;</code>
     * @return bool
     */
    public function getGetsNotified()
    {
        return $this->getsNotified;
    }

    /**
     * Generated from protobuf field <code>bool getsNotified = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setGetsNotified($var)
    {
        GPBUtil::checkBool($var);
        $this->getsNotified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool canDelete = 5;</code>
     * @return bool
     */
    public function getCanDelete()
    {
        return $this->canDelete;
    }

    /**
     * Generated from protobuf field <code>bool canDelete = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanDelete($var)
    {
        GPBUtil::checkBool($var);
        $this->canDelete = $var;

        return $this;
    }

}

