<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetAmenityEdge</code>
 */
class AssetAmenityEdge extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id amenityId = 1;</code>
     */
    private $amenityId = null;
    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount price = 2;</code>
     */
    private $price = null;
    /**
     * Generated from protobuf field <code>string note = 3;</code>
     */
    private $note = '';
    /**
     * Generated from protobuf field <code>bool suppressed = 4;</code>
     */
    private $suppressed = false;
    /**
     * Generated from protobuf field <code>string description = 5;</code>
     */
    private $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $amenityId
     *     @type \App\Types\CurrencyAmount $price
     *     @type string $note
     *     @type bool $suppressed
     *     @type string $description
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id amenityId = 1;</code>
     * @return \App\Types\Id
     */
    public function getAmenityId()
    {
        return $this->amenityId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id amenityId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setAmenityId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->amenityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount price = 2;</code>
     * @return \App\Types\CurrencyAmount
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount price = 2;</code>
     * @param \App\Types\CurrencyAmount $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkMessage($var, \App\Types\CurrencyAmount::class);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 3;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->note = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool suppressed = 4;</code>
     * @return bool
     */
    public function getSuppressed()
    {
        return $this->suppressed;
    }

    /**
     * Generated from protobuf field <code>bool suppressed = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuppressed($var)
    {
        GPBUtil::checkBool($var);
        $this->suppressed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

