<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetI_UserI_Permissions</code>
 */
class AssetI_UserI_Permissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     */
    private $assetId = null;
    /**
     * Generated from protobuf field <code>.zipcube.Id userId = 2;</code>
     */
    private $userId = null;
    /**
     * Generated from protobuf field <code>.zipcube.AssetPermissions permissions = 3;</code>
     */
    private $permissions = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $assetId
     *     @type \App\Types\Id $userId
     *     @type \App\Types\AssetPermissions $permissions
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @return \App\Types\Id
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->assetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id userId = 2;</code>
     * @return \App\Types\Id
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id userId = 2;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.AssetPermissions permissions = 3;</code>
     * @return \App\Types\AssetPermissions
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * Generated from protobuf field <code>.zipcube.AssetPermissions permissions = 3;</code>
     * @param \App\Types\AssetPermissions $var
     * @return $this
     */
    public function setPermissions($var)
    {
        GPBUtil::checkMessage($var, \App\Types\AssetPermissions::class);
        $this->permissions = $var;

        return $this;
    }

}

