<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.AssetI_AssetType</code>
 */
class AssetI_AssetType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     */
    private $assetId = null;
    /**
     * Generated from protobuf field <code>.zipcube.AssetType type = 2;</code>
     */
    private $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $assetId
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @return \App\Types\Id
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id assetId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->assetId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.AssetType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.zipcube.AssetType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \App\Types\AssetType::class);
        $this->type = $var;

        return $this;
    }

}

