<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.AssetType</code>
 */
class AssetType
{
    /**
     * Generated from protobuf enum <code>NOASSETTYPE = 0;</code>
     */
    const NOASSETTYPE = 0;
    /**
     * Generated from protobuf enum <code>GROUP = 1;</code>
     */
    const GROUP = 1;
    /**
     * Generated from protobuf enum <code>VENUE = 2;</code>
     */
    const VENUE = 2;
    /**
     * Generated from protobuf enum <code>ROOM = 3;</code>
     */
    const ROOM = 3;

    private static $valueToName = [
        self::NOASSETTYPE => 'NOASSETTYPE',
        self::GROUP => 'GROUP',
        self::VENUE => 'VENUE',
        self::ROOM => 'ROOM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

