<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.BookingConstraints</code>
 */
class BookingConstraints extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.PeopleBookingConstraints guests = 1;</code>
     */
    private $guests = null;
    /**
     * Generated from protobuf field <code>.zipcube.TimeBookingConstraints duration = 2;</code>
     */
    private $duration = null;
    /**
     * Generated from protobuf field <code>.zipcube.SpendBookingConstraints spend = 3;</code>
     */
    private $spend = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\PeopleBookingConstraints $guests
     *     @type \App\Types\TimeBookingConstraints $duration
     *     @type \App\Types\SpendBookingConstraints $spend
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.PeopleBookingConstraints guests = 1;</code>
     * @return \App\Types\PeopleBookingConstraints
     */
    public function getGuests()
    {
        return $this->guests;
    }

    /**
     * Generated from protobuf field <code>.zipcube.PeopleBookingConstraints guests = 1;</code>
     * @param \App\Types\PeopleBookingConstraints $var
     * @return $this
     */
    public function setGuests($var)
    {
        GPBUtil::checkMessage($var, \App\Types\PeopleBookingConstraints::class);
        $this->guests = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.TimeBookingConstraints duration = 2;</code>
     * @return \App\Types\TimeBookingConstraints
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>.zipcube.TimeBookingConstraints duration = 2;</code>
     * @param \App\Types\TimeBookingConstraints $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkMessage($var, \App\Types\TimeBookingConstraints::class);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.SpendBookingConstraints spend = 3;</code>
     * @return \App\Types\SpendBookingConstraints
     */
    public function getSpend()
    {
        return $this->spend;
    }

    /**
     * Generated from protobuf field <code>.zipcube.SpendBookingConstraints spend = 3;</code>
     * @param \App\Types\SpendBookingConstraints $var
     * @return $this
     */
    public function setSpend($var)
    {
        GPBUtil::checkMessage($var, \App\Types\SpendBookingConstraints::class);
        $this->spend = $var;

        return $this;
    }

}

