<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.Configuration</code>
 */
class Configuration
{
    /**
     * Generated from protobuf enum <code>NOCONFIGURATION = 0;</code>
     */
    const NOCONFIGURATION = 0;
    /**
     * Generated from protobuf enum <code>SEATED = 1;</code>
     */
    const SEATED = 1;
    /**
     * Generated from protobuf enum <code>RECEPTION = 2;</code>
     */
    const RECEPTION = 2;
    /**
     * Generated from protobuf enum <code>BOARDROOM = 3;</code>
     */
    const BOARDROOM = 3;
    /**
     * Generated from protobuf enum <code>CLASSROOM = 4;</code>
     */
    const CLASSROOM = 4;
    /**
     * Generated from protobuf enum <code>BANQUET = 5;</code>
     */
    const BANQUET = 5;
    /**
     * Generated from protobuf enum <code>THEATRE = 6;</code>
     */
    const THEATRE = 6;
    /**
     * Generated from protobuf enum <code>U_SHAPED = 7;</code>
     */
    const U_SHAPED = 7;
    /**
     * Generated from protobuf enum <code>CABARET = 8;</code>
     */
    const CABARET = 8;

    private static $valueToName = [
        self::NOCONFIGURATION => 'NOCONFIGURATION',
        self::SEATED => 'SEATED',
        self::RECEPTION => 'RECEPTION',
        self::BOARDROOM => 'BOARDROOM',
        self::CLASSROOM => 'CLASSROOM',
        self::BANQUET => 'BANQUET',
        self::THEATRE => 'THEATRE',
        self::U_SHAPED => 'U_SHAPED',
        self::CABARET => 'CABARET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

