<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.Day</code>
 */
class Day
{
    /**
     * Generated from protobuf enum <code>NODAY = 0;</code>
     */
    const NODAY = 0;
    /**
     * Generated from protobuf enum <code>SUNDAY = 1;</code>
     */
    const SUNDAY = 1;
    /**
     * Generated from protobuf enum <code>MONDAY = 2;</code>
     */
    const MONDAY = 2;
    /**
     * Generated from protobuf enum <code>TUESDAY = 3;</code>
     */
    const TUESDAY = 3;
    /**
     * Generated from protobuf enum <code>WEDNESDAY = 4;</code>
     */
    const WEDNESDAY = 4;
    /**
     * Generated from protobuf enum <code>THURSDAY = 5;</code>
     */
    const THURSDAY = 5;
    /**
     * Generated from protobuf enum <code>FRIDAY = 6;</code>
     */
    const FRIDAY = 6;
    /**
     * Generated from protobuf enum <code>SATURDAY = 7;</code>
     */
    const SATURDAY = 7;

    private static $valueToName = [
        self::NODAY => 'NODAY',
        self::SUNDAY => 'SUNDAY',
        self::MONDAY => 'MONDAY',
        self::TUESDAY => 'TUESDAY',
        self::WEDNESDAY => 'WEDNESDAY',
        self::THURSDAY => 'THURSDAY',
        self::FRIDAY => 'FRIDAY',
        self::SATURDAY => 'SATURDAY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

