<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.Image</code>
 */
class Image extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>.zipcube.ImageType type = 2;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageUrl imageUrls = 3;</code>
     */
    private $imageUrls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $id
     *     @type int $type
     *     @type \App\Types\ImageUrl[]|\Google\Protobuf\Internal\RepeatedField $imageUrls
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @return \App\Types\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ImageType type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ImageType type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \App\Types\ImageType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageUrl imageUrls = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImageUrls()
    {
        return $this->imageUrls;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageUrl imageUrls = 3;</code>
     * @param \App\Types\ImageUrl[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImageUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\ImageUrl::class);
        $this->imageUrls = $arr;

        return $this;
    }

}

