<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.ImageSize</code>
 */
class ImageSize
{
    /**
     * Generated from protobuf enum <code>RAW = 0;</code>
     */
    const RAW = 0;
    /**
     * Generated from protobuf enum <code>SMALL = 1;</code>
     */
    const SMALL = 1;
    /**
     * Generated from protobuf enum <code>MEDIUM = 2;</code>
     */
    const MEDIUM = 2;
    /**
     * Generated from protobuf enum <code>LARGE = 3;</code>
     */
    const LARGE = 3;
    /**
     * Generated from protobuf enum <code>HUGE = 4;</code>
     */
    const HUGE = 4;
    /**
     * Generated from protobuf enum <code>BANNER = 5;</code>
     */
    const BANNER = 5;

    private static $valueToName = [
        self::RAW => 'RAW',
        self::SMALL => 'SMALL',
        self::MEDIUM => 'MEDIUM',
        self::LARGE => 'LARGE',
        self::HUGE => 'HUGE',
        self::BANNER => 'BANNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

