<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ImageUrl</code>
 */
class ImageUrl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string url = 1;</code>
     */
    private $url = '';
    /**
     * Generated from protobuf field <code>.zipcube.ImageSize imageSize = 2;</code>
     */
    private $imageSize = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *     @type int $imageSize
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ImageSize imageSize = 2;</code>
     * @return int
     */
    public function getImageSize()
    {
        return $this->imageSize;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ImageSize imageSize = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setImageSize($var)
    {
        GPBUtil::checkEnum($var, \App\Types\ImageSize::class);
        $this->imageSize = $var;

        return $this;
    }

}

