<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ImageEdge</code>
 */
class ImageEdge extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id imageId = 1;</code>
     */
    private $imageId = null;
    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     */
    private $orderIndex = 0;
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    private $description = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $imageId
     *     @type int $orderIndex
     *     @type string $description
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id imageId = 1;</code>
     * @return \App\Types\Id
     */
    public function getImageId()
    {
        return $this->imageId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id imageId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setImageId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->imageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     * @return int
     */
    public function getOrderIndex()
    {
        return $this->orderIndex;
    }

    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

