<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ImposingAssets</code>
 */
class ImposingAssets extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Asset template = 1;</code>
     */
    private $template = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.Asset targets = 2;</code>
     */
    private $targets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Asset $template
     *     @type \App\Types\Asset[]|\Google\Protobuf\Internal\RepeatedField $targets
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Asset template = 1;</code>
     * @return \App\Types\Asset
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Asset template = 1;</code>
     * @param \App\Types\Asset $var
     * @return $this
     */
    public function setTemplate($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Asset::class);
        $this->template = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Asset targets = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Asset targets = 2;</code>
     * @param \App\Types\Asset[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\Asset::class);
        $this->targets = $arr;

        return $this;
    }

}

