<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.Menu</code>
 */
class Menu extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string description = 1;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuGroup groups = 2;</code>
     */
    private $groups;
    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuPriceOption priceOptions = 3;</code>
     */
    private $priceOptions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $description
     *     @type \App\Types\MenuGroup[]|\Google\Protobuf\Internal\RepeatedField $groups
     *     @type \App\Types\MenuPriceOption[]|\Google\Protobuf\Internal\RepeatedField $priceOptions
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuGroup groups = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuGroup groups = 2;</code>
     * @param \App\Types\MenuGroup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\MenuGroup::class);
        $this->groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuPriceOption priceOptions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPriceOptions()
    {
        return $this->priceOptions;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.MenuPriceOption priceOptions = 3;</code>
     * @param \App\Types\MenuPriceOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPriceOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\MenuPriceOption::class);
        $this->priceOptions = $arr;

        return $this;
    }

}

