<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.Month</code>
 */
class Month
{
    /**
     * Generated from protobuf enum <code>NOMONTH = 0;</code>
     */
    const NOMONTH = 0;
    /**
     * Generated from protobuf enum <code>JANUARY = 1;</code>
     */
    const JANUARY = 1;
    /**
     * Generated from protobuf enum <code>FEBRUARY = 2;</code>
     */
    const FEBRUARY = 2;
    /**
     * Generated from protobuf enum <code>MARCH = 3;</code>
     */
    const MARCH = 3;
    /**
     * Generated from protobuf enum <code>APRIL = 4;</code>
     */
    const APRIL = 4;
    /**
     * Generated from protobuf enum <code>MAY = 5;</code>
     */
    const MAY = 5;
    /**
     * Generated from protobuf enum <code>JUNE = 6;</code>
     */
    const JUNE = 6;
    /**
     * Generated from protobuf enum <code>JULY = 7;</code>
     */
    const JULY = 7;
    /**
     * Generated from protobuf enum <code>AUGUST = 8;</code>
     */
    const AUGUST = 8;
    /**
     * Generated from protobuf enum <code>SEPTEMBER = 9;</code>
     */
    const SEPTEMBER = 9;
    /**
     * Generated from protobuf enum <code>OCTOBER = 10;</code>
     */
    const OCTOBER = 10;
    /**
     * Generated from protobuf enum <code>NOVEMBER = 11;</code>
     */
    const NOVEMBER = 11;
    /**
     * Generated from protobuf enum <code>DECEMBER = 12;</code>
     */
    const DECEMBER = 12;

    private static $valueToName = [
        self::NOMONTH => 'NOMONTH',
        self::JANUARY => 'JANUARY',
        self::FEBRUARY => 'FEBRUARY',
        self::MARCH => 'MARCH',
        self::APRIL => 'APRIL',
        self::MAY => 'MAY',
        self::JUNE => 'JUNE',
        self::JULY => 'JULY',
        self::AUGUST => 'AUGUST',
        self::SEPTEMBER => 'SEPTEMBER',
        self::OCTOBER => 'OCTOBER',
        self::NOVEMBER => 'NOVEMBER',
        self::DECEMBER => 'DECEMBER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

