<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.NearbyPlace</code>
 */
class NearbyPlace extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.zipcube.Length distance = 2;</code>
     */
    private $distance = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.NearbyPlaceType types = 3;</code>
     */
    private $types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \App\Types\Length $distance
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $types
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Length distance = 2;</code>
     * @return \App\Types\Length
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Length distance = 2;</code>
     * @param \App\Types\Length $var
     * @return $this
     */
    public function setDistance($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Length::class);
        $this->distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.NearbyPlaceType types = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypes()
    {
        return $this->types;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.NearbyPlaceType types = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \App\Types\NearbyPlaceType::class);
        $this->types = $arr;

        return $this;
    }

}

