<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.NearbyPlaceType</code>
 */
class NearbyPlaceType
{
    /**
     * Generated from protobuf enum <code>NONEARBYPLACETYPE = 0;</code>
     */
    const NONEARBYPLACETYPE = 0;
    /**
     * Generated from protobuf enum <code>TRAIN_STATION = 1;</code>
     */
    const TRAIN_STATION = 1;
    /**
     * Generated from protobuf enum <code>SUBWAY_STATION = 2;</code>
     */
    const SUBWAY_STATION = 2;

    private static $valueToName = [
        self::NONEARBYPLACETYPE => 'NONEARBYPLACETYPE',
        self::TRAIN_STATION => 'TRAIN_STATION',
        self::SUBWAY_STATION => 'SUBWAY_STATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

