<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.Period</code>
 */
class Period extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.DateTime start = 1;</code>
     */
    private $start = null;
    /**
     * Generated from protobuf field <code>.zipcube.DateTime end = 2;</code>
     */
    private $end = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\DateTime $start
     *     @type \App\Types\DateTime $end
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.DateTime start = 1;</code>
     * @return \App\Types\DateTime
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>.zipcube.DateTime start = 1;</code>
     * @param \App\Types\DateTime $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkMessage($var, \App\Types\DateTime::class);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.DateTime end = 2;</code>
     * @return \App\Types\DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }

    /**
     * Generated from protobuf field <code>.zipcube.DateTime end = 2;</code>
     * @param \App\Types\DateTime $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkMessage($var, \App\Types\DateTime::class);
        $this->end = $var;

        return $this;
    }

}

