<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.PriceCoverage</code>
 */
class PriceCoverage
{
    /**
     * Generated from protobuf enum <code>NOPRICECOVERAGE = 0;</code>
     */
    const NOPRICECOVERAGE = 0;
    /**
     * Generated from protobuf enum <code>ALLIN = 1;</code>
     */
    const ALLIN = 1;
    /**
     * Generated from protobuf enum <code>MINIMUMSPEND = 2;</code>
     */
    const MINIMUMSPEND = 2;
    /**
     * Generated from protobuf enum <code>FLATRATE = 3;</code>
     */
    const FLATRATE = 3;

    private static $valueToName = [
        self::NOPRICECOVERAGE => 'NOPRICECOVERAGE',
        self::ALLIN => 'ALLIN',
        self::MINIMUMSPEND => 'MINIMUMSPEND',
        self::FLATRATE => 'FLATRATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

