<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ProductBookingParameters</code>
 */
class ProductBookingParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.BookingConstraints constraints = 1;</code>
     */
    private $constraints = null;
    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount depositAmount = 2;</code>
     */
    private $depositAmount = null;
    /**
     * Generated from protobuf field <code>float depositPercent = 3;</code>
     */
    private $depositPercent = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\BookingConstraints $constraints
     *     @type \App\Types\CurrencyAmount $depositAmount
     *     @type float $depositPercent
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.BookingConstraints constraints = 1;</code>
     * @return \App\Types\BookingConstraints
     */
    public function getConstraints()
    {
        return $this->constraints;
    }

    /**
     * Generated from protobuf field <code>.zipcube.BookingConstraints constraints = 1;</code>
     * @param \App\Types\BookingConstraints $var
     * @return $this
     */
    public function setConstraints($var)
    {
        GPBUtil::checkMessage($var, \App\Types\BookingConstraints::class);
        $this->constraints = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount depositAmount = 2;</code>
     * @return \App\Types\CurrencyAmount
     */
    public function getDepositAmount()
    {
        return $this->depositAmount;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount depositAmount = 2;</code>
     * @param \App\Types\CurrencyAmount $var
     * @return $this
     */
    public function setDepositAmount($var)
    {
        GPBUtil::checkMessage($var, \App\Types\CurrencyAmount::class);
        $this->depositAmount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float depositPercent = 3;</code>
     * @return float
     */
    public function getDepositPercent()
    {
        return $this->depositPercent;
    }

    /**
     * Generated from protobuf field <code>float depositPercent = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDepositPercent($var)
    {
        GPBUtil::checkFloat($var);
        $this->depositPercent = $var;

        return $this;
    }

}

