<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.ProductCategory</code>
 */
class ProductCategory
{
    /**
     * Generated from protobuf enum <code>NOPRODUCTCATEGORY = 0;</code>
     */
    const NOPRODUCTCATEGORY = 0;
    /**
     * Generated from protobuf enum <code>MEETING = 1;</code>
     */
    const MEETING = 1;
    /**
     * Generated from protobuf enum <code>OFFICE = 2;</code>
     */
    const OFFICE = 2;
    /**
     * Generated from protobuf enum <code>PARTY = 3;</code>
     */
    const PARTY = 3;
    /**
     * Generated from protobuf enum <code>WEDDING = 4;</code>
     */
    const WEDDING = 4;
    /**
     * Generated from protobuf enum <code>DINING = 5;</code>
     */
    const DINING = 5;
    /**
     * Generated from protobuf enum <code>HOTDESK = 6;</code>
     */
    const HOTDESK = 6;
    /**
     * Generated from protobuf enum <code>DEDICATEDDESK = 7;</code>
     */
    const DEDICATEDDESK = 7;

    private static $valueToName = [
        self::NOPRODUCTCATEGORY => 'NOPRODUCTCATEGORY',
        self::MEETING => 'MEETING',
        self::OFFICE => 'OFFICE',
        self::PARTY => 'PARTY',
        self::WEDDING => 'WEDDING',
        self::DINING => 'DINING',
        self::HOTDESK => 'HOTDESK',
        self::DEDICATEDDESK => 'DEDICATEDDESK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

