<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount unitPrice = 3;</code>
     */
    private $unitPrice = null;
    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 4;</code>
     */
    private $context = null;
    /**
     * Generated from protobuf field <code>.zipcube.TimeUnit unit = 5;</code>
     */
    private $unit = 0;
    /**
     * Generated from protobuf field <code>.zipcube.PriceCoverage coverage = 6;</code>
     */
    private $coverage = 0;
    /**
     * Generated from protobuf field <code>string description = 7;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>repeated .zipcube.ProductItem includes = 8;</code>
     */
    private $includes;
    /**
     * Generated from protobuf field <code>.zipcube.ProductBookingParameters parameters = 9;</code>
     */
    private $parameters = null;
    /**
     * Generated from protobuf field <code>bool perPerson = 10;</code>
     */
    private $perPerson = false;
    /**
     * Generated from protobuf field <code>int32 stock = 11;</code>
     */
    private $stock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $id
     *     @type string $name
     *     @type \App\Types\CurrencyAmount $unitPrice
     *     @type \App\Types\ProductContext $context
     *     @type int $unit
     *     @type int $coverage
     *     @type string $description
     *     @type \App\Types\ProductItem[]|\Google\Protobuf\Internal\RepeatedField $includes
     *     @type \App\Types\ProductBookingParameters $parameters
     *     @type bool $perPerson
     *     @type int $stock
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @return \App\Types\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount unitPrice = 3;</code>
     * @return \App\Types\CurrencyAmount
     */
    public function getUnitPrice()
    {
        return $this->unitPrice;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount unitPrice = 3;</code>
     * @param \App\Types\CurrencyAmount $var
     * @return $this
     */
    public function setUnitPrice($var)
    {
        GPBUtil::checkMessage($var, \App\Types\CurrencyAmount::class);
        $this->unitPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 4;</code>
     * @return \App\Types\ProductContext
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 4;</code>
     * @param \App\Types\ProductContext $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \App\Types\ProductContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.TimeUnit unit = 5;</code>
     * @return int
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * Generated from protobuf field <code>.zipcube.TimeUnit unit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkEnum($var, \App\Types\TimeUnit::class);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.PriceCoverage coverage = 6;</code>
     * @return int
     */
    public function getCoverage()
    {
        return $this->coverage;
    }

    /**
     * Generated from protobuf field <code>.zipcube.PriceCoverage coverage = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCoverage($var)
    {
        GPBUtil::checkEnum($var, \App\Types\PriceCoverage::class);
        $this->coverage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ProductItem includes = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIncludes()
    {
        return $this->includes;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ProductItem includes = 8;</code>
     * @param \App\Types\ProductItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIncludes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\ProductItem::class);
        $this->includes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductBookingParameters parameters = 9;</code>
     * @return \App\Types\ProductBookingParameters
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductBookingParameters parameters = 9;</code>
     * @param \App\Types\ProductBookingParameters $var
     * @return $this
     */
    public function setParameters($var)
    {
        GPBUtil::checkMessage($var, \App\Types\ProductBookingParameters::class);
        $this->parameters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool perPerson = 10;</code>
     * @return bool
     */
    public function getPerPerson()
    {
        return $this->perPerson;
    }

    /**
     * Generated from protobuf field <code>bool perPerson = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setPerPerson($var)
    {
        GPBUtil::checkBool($var);
        $this->perPerson = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 stock = 11;</code>
     * @return int
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Generated from protobuf field <code>int32 stock = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->stock = $var;

        return $this;
    }

}

