<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ProductPriceSchedule</code>
 */
class ProductPriceSchedule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .zipcube.DailyHours days = 1;</code>
     */
    private $days;
    /**
     * Generated from protobuf field <code>repeated int32 weeks = 2;</code>
     */
    private $weeks;
    /**
     * Generated from protobuf field <code>repeated .zipcube.Month months = 3;</code>
     */
    private $months;
    /**
     * Generated from protobuf field <code>.zipcube.Period period = 4;</code>
     */
    private $period = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\DailyHours[]|\Google\Protobuf\Internal\RepeatedField $days
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $weeks
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $months
     *     @type \App\Types\Period $period
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.DailyHours days = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDays()
    {
        return $this->days;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.DailyHours days = 1;</code>
     * @param \App\Types\DailyHours[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDays($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\DailyHours::class);
        $this->days = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 weeks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWeeks()
    {
        return $this->weeks;
    }

    /**
     * Generated from protobuf field <code>repeated int32 weeks = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWeeks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->weeks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Month months = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMonths()
    {
        return $this->months;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Month months = 3;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMonths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \App\Types\Month::class);
        $this->months = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Period period = 4;</code>
     * @return \App\Types\Period
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Period period = 4;</code>
     * @param \App\Types\Period $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Period::class);
        $this->period = $var;

        return $this;
    }

}

