<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.ProductContext</code>
 */
class ProductContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string website = 1;</code>
     */
    private $website = '';
    /**
     * Generated from protobuf field <code>.zipcube.ProductPriceSchedule schedule = 2;</code>
     */
    private $schedule = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetConfiguration configurations = 3;</code>
     */
    private $configurations;
    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetAmenityEdge amenities = 4;</code>
     */
    private $amenities;
    /**
     * Generated from protobuf field <code>repeated .zipcube.TagEdge tags = 5;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>repeated .zipcube.Menu menus = 6;</code>
     */
    private $menus;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $website
     *     @type \App\Types\ProductPriceSchedule $schedule
     *     @type \App\Types\AssetConfiguration[]|\Google\Protobuf\Internal\RepeatedField $configurations
     *     @type \App\Types\AssetAmenityEdge[]|\Google\Protobuf\Internal\RepeatedField $amenities
     *     @type \App\Types\TagEdge[]|\Google\Protobuf\Internal\RepeatedField $tags
     *     @type \App\Types\Menu[]|\Google\Protobuf\Internal\RepeatedField $menus
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string website = 1;</code>
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    /**
     * Generated from protobuf field <code>string website = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWebsite($var)
    {
        GPBUtil::checkString($var, True);
        $this->website = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductPriceSchedule schedule = 2;</code>
     * @return \App\Types\ProductPriceSchedule
     */
    public function getSchedule()
    {
        return $this->schedule;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductPriceSchedule schedule = 2;</code>
     * @param \App\Types\ProductPriceSchedule $var
     * @return $this
     */
    public function setSchedule($var)
    {
        GPBUtil::checkMessage($var, \App\Types\ProductPriceSchedule::class);
        $this->schedule = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetConfiguration configurations = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConfigurations()
    {
        return $this->configurations;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetConfiguration configurations = 3;</code>
     * @param \App\Types\AssetConfiguration[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConfigurations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\AssetConfiguration::class);
        $this->configurations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetAmenityEdge amenities = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAmenities()
    {
        return $this->amenities;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.AssetAmenityEdge amenities = 4;</code>
     * @param \App\Types\AssetAmenityEdge[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAmenities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\AssetAmenityEdge::class);
        $this->amenities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.TagEdge tags = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.TagEdge tags = 5;</code>
     * @param \App\Types\TagEdge[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\TagEdge::class);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Menu menus = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMenus()
    {
        return $this->menus;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Menu menus = 6;</code>
     * @param \App\Types\Menu[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMenus($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\Menu::class);
        $this->menus = $arr;

        return $this;
    }

}

