<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.SpendBookingConstraints</code>
 */
class SpendBookingConstraints extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount minSpendAmount = 1;</code>
     */
    private $minSpendAmount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\CurrencyAmount $minSpendAmount
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount minSpendAmount = 1;</code>
     * @return \App\Types\CurrencyAmount
     */
    public function getMinSpendAmount()
    {
        return $this->minSpendAmount;
    }

    /**
     * Generated from protobuf field <code>.zipcube.CurrencyAmount minSpendAmount = 1;</code>
     * @param \App\Types\CurrencyAmount $var
     * @return $this
     */
    public function setMinSpendAmount($var)
    {
        GPBUtil::checkMessage($var, \App\Types\CurrencyAmount::class);
        $this->minSpendAmount = $var;

        return $this;
    }

}

