<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.TagCatalogItem</code>
 */
class TagCatalogItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Tag tag = 1;</code>
     */
    private $tag = null;
    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     */
    private $orderIndex = 0;
    /**
     * Generated from protobuf field <code>.zipcube.ProductCategory productCategory = 3;</code>
     */
    private $productCategory = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Tag $tag
     *     @type int $orderIndex
     *     @type int $productCategory
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Tag tag = 1;</code>
     * @return \App\Types\Tag
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Tag tag = 1;</code>
     * @param \App\Types\Tag $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Tag::class);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     * @return int
     */
    public function getOrderIndex()
    {
        return $this->orderIndex;
    }

    /**
     * Generated from protobuf field <code>int32 orderIndex = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderIndex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductCategory productCategory = 3;</code>
     * @return int
     */
    public function getProductCategory()
    {
        return $this->productCategory;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductCategory productCategory = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setProductCategory($var)
    {
        GPBUtil::checkEnum($var, \App\Types\ProductCategory::class);
        $this->productCategory = $var;

        return $this;
    }

}

