<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.TagEdge</code>
 */
class TagEdge extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id tagId = 1;</code>
     */
    private $tagId = null;
    /**
     * Generated from protobuf field <code>bool suppressed = 2;</code>
     */
    private $suppressed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $tagId
     *     @type bool $suppressed
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id tagId = 1;</code>
     * @return \App\Types\Id
     */
    public function getTagId()
    {
        return $this->tagId;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id tagId = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setTagId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->tagId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool suppressed = 2;</code>
     * @return bool
     */
    public function getSuppressed()
    {
        return $this->suppressed;
    }

    /**
     * Generated from protobuf field <code>bool suppressed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuppressed($var)
    {
        GPBUtil::checkBool($var);
        $this->suppressed = $var;

        return $this;
    }

}

