<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.TimeBookingConstraints</code>
 */
class TimeBookingConstraints extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 minDuration = 1;</code>
     */
    private $minDuration = 0;
    /**
     * Generated from protobuf field <code>int32 maxDuration = 2;</code>
     */
    private $maxDuration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $minDuration
     *     @type int $maxDuration
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 minDuration = 1;</code>
     * @return int
     */
    public function getMinDuration()
    {
        return $this->minDuration;
    }

    /**
     * Generated from protobuf field <code>int32 minDuration = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMinDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->minDuration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 maxDuration = 2;</code>
     * @return int
     */
    public function getMaxDuration()
    {
        return $this->maxDuration;
    }

    /**
     * Generated from protobuf field <code>int32 maxDuration = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxDuration($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxDuration = $var;

        return $this;
    }

}

