<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.UserRole</code>
 */
class UserRole
{
    /**
     * Generated from protobuf enum <code>LOGGEDIN = 0;</code>
     */
    const LOGGEDIN = 0;
    /**
     * Generated from protobuf enum <code>ADMIN = 1;</code>
     */
    const ADMIN = 1;
    /**
     * Generated from protobuf enum <code>VENUEOWNER = 2;</code>
     */
    const VENUEOWNER = 2;

    private static $valueToName = [
        self::LOGGEDIN => 'LOGGEDIN',
        self::ADMIN => 'ADMIN',
        self::VENUEOWNER => 'VENUEOWNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

