<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/assets.proto

namespace App\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.UserClaims</code>
 */
class UserClaims extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.UserClaim user = 1;</code>
     */
    private $user = null;
    /**
     * Generated from protobuf field <code>.zipcube.UserClaim actor = 2;</code>
     */
    private $actor = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\UserClaim $user
     *     @type \App\Types\UserClaim $actor
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Assets::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.UserClaim user = 1;</code>
     * @return \App\Types\UserClaim
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.zipcube.UserClaim user = 1;</code>
     * @param \App\Types\UserClaim $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \App\Types\UserClaim::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.UserClaim actor = 2;</code>
     * @return \App\Types\UserClaim
     */
    public function getActor()
    {
        return $this->actor;
    }

    /**
     * Generated from protobuf field <code>.zipcube.UserClaim actor = 2;</code>
     * @param \App\Types\UserClaim $var
     * @return $this
     */
    public function setActor($var)
    {
        GPBUtil::checkMessage($var, \App\Types\UserClaim::class);
        $this->actor = $var;

        return $this;
    }

}

