/* tslint:disable:max-line-length */
import { AmenityGroup, AmenityMeta, ProductCategory } from '@src/core/domain';
import { Catalog } from '@src/core';

const all = null;

const office = [ProductCategory.OFFICE];
const meetingPartyWedding = [
  ProductCategory.MEETING,
  ProductCategory.PARTY,
  ProductCategory.WEDDING,
];
const meetingPartyDining = [
  ProductCategory.MEETING,
  ProductCategory.PARTY,
  ProductCategory.DINING,
];
const meetingPartyDiningWedding = [
  ProductCategory.MEETING,
  ProductCategory.PARTY,
  ProductCategory.DINING,
  ProductCategory.WEDDING,
];
const partyWedding = [
  ProductCategory.PARTY,
  ProductCategory.WEDDING,
];
const dining = [ProductCategory.DINING];

const _itemsSource: AmenityMeta[] = [
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.wifi',
    id: '15',
    inProductCategories: all,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/wireless-internet-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.smoking_area',
    id: '-138',
    inProductCategories: all,
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.accessible',
    inProductCategories: all,
    id: '23',
    isCustomisable: true,
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.reception',
    id: '-7',
    inProductCategories: all,
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.free_parking_on_premise',
    id: '-6',
    inProductCategories: all,
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.breakout_spaces_shared',
    id: '-2',
    inProductCategories: all,
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.air_conditioning',
    id: '-129',
    inProductCategories: all,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/air-conditioning-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.GENERAL,
    amenitySectionId: 1,
    description: 'listing.pets_allowed',
    id: '-26',
    inProductCategories: all,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.cleaning',
    id: '-135',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.printing',
    id: '-13',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.bike_storage',
    id: '-19',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.mailing_address',
    id: '-9',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.trading_address',
    id: '-14',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.cafe',
    id: '-20',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.lockers',
    id: '-25',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.meeting_rooms_on_site',
    id: '-11',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.secure_access',
    id: '-15',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.childcare',
    id: '-21',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.phone_booths',
    id: '-12',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.twenty_four_hour_access',
    id: '-16',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.OFFICE_AMENITIES,
    amenitySectionId: 1,
    description: 'listing.gym',
    id: '-24',
    inProductCategories: office,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.flipchart',
    id: '24',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.audio_recording',
    id: '-32',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.whiteboards',
    id: '19',
    inProductCategories: meetingPartyWedding,
    isCustomisable: true,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.stationary_pen_paper',
    id: '25',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.video_conference_phone',
    id: '18',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.projector_tv_screen',
    id: '26',
    isCustomisable: true,
    isPriceable: true,
    inProductCategories: meetingPartyWedding,
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.microphone',
    id: '-5',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/mic-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.speakers',
    id: '-131',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/speaker-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EQUIPMENTS,
    amenitySectionId: 1,
    description: 'listing.conferencing_phone',
    id: '20',
    inProductCategories: meetingPartyWedding,
    isPriceable: true,
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.on_site_technical_support',
    id: '-4',
    inProductCategories: meetingPartyDiningWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/technical-support-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.master_of_ceremonies_toastmaster',
    id: '-122',
    inProductCategories: meetingPartyDiningWedding,
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.hostess',
    id: '-139',
    inProductCategories: meetingPartyDiningWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/hostess-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.ticketing_event_possible',
    id: '-143',
    inProductCategories: meetingPartyDiningWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/ticketing-event-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.event_coordinator',
    id: '-141',
    inProductCategories: meetingPartyDiningWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/suitable-for-events-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.VENUE_STAFF,
    amenitySectionId: 1,
    description: 'listing.security_staff',
    id: '-142',
    inProductCategories: meetingPartyDiningWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/security-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.cloakroom',
    id: '-140',
    inProductCategories: partyWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/cloakroom-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.hot_tub',
    id: '-34',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.outside_space',
    id: '-137',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.helipad',
    id: '-127',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.confetti_permitted',
    id: '-126',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.OTHER,
    amenitySectionId: 1,
    description: 'listing.pool',
    id: '-33',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.can_bring_your_own_catering',
    id: '28',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.space_for_own_catering_equipment',
    id: '-38',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.tens_available',
    id: '-43',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.can_bring_own_alcohol',
    id: '-35',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.kitchen',
    id: '-135',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.civil_ceremony_licence_venue',
    id: '-95',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.professional_kitchen',
    id: '-39',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.catering_equipment_available',
    id: '-37',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CATERING_LICENCE,
    amenitySectionId: 2,
    description: 'listing.alcohol_licence',
    id: '-44',
    inProductCategories: meetingPartyDining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.american',
    id: '-51',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.chinese',
    id: '-56',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.greek',
    id: '-60',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.mediterranean',
    id: '-64',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.peruvian',
    id: '-68',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.spanish',
    id: '-72',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.asian',
    id: '-52',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.english',
    id: '-57',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.mexican',
    id: '-65',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.polish',
    id: '-69',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.vietnamese',
    id: '-77',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.french',
    id: '-58',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.italian',
    id: '-62',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.middle_eastern',
    id: '-66',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.russian',
    id: '-70',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.brazilian',
    id: '-55',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.japanese',
    id: '-63',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.nordic',
    id: '-67',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.thai',
    id: '-75',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.steakhouse',
    id: '-73',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.barbecue',
    id: '-54',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.tapas_small_plates',
    id: '-74',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.gastro_pub',
    id: '-59',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.seafood',
    id: '-71',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.vegetarian_vegan',
    id: '-76',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.CUISINE,
    amenitySectionId: 2,
    description: 'listing.vegan',
    id: '-78',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.vegetarian_vegan',
    id: '-76',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.vegan',
    id: '-78',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.can_provide_kosher',
    id: '-40',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.gluten_free',
    id: '-79',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.lactose_intolerant',
    id: '-80',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.DIETARY,
    amenitySectionId: 2,
    description: 'listing.can_provide_halal',
    id: '-41',
    inProductCategories: dining,
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.evening_reception_facilities',
    id: '-114',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.marquee_available',
    id: '-115',
    inProductCategories: partyWedding,
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.dance_floor',
    id: '-116',
    inProductCategories: partyWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/dance-floor-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.entertainment_license',
    id: '-117',
    inProductCategories: partyWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/entertainment-licence-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.live_band_facilities',
    id: '-118',
    inProductCategories: partyWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/live-music-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.dj_facilities',
    id: '-119',
    inProductCategories: partyWedding,
    imageUrl: 'https://65dd94d74e66e2a2a076-b0c2c220483ae2331d7eb36213a5b418.ssl.cf3.rackcdn.com/amenities/dj-facilities-4x.png',
  },
  {
    amenityGroupId: AmenityGroup.EVENING_ENTERTAINMENT,
    amenitySectionId: 1,
    description: 'listing.outdoor_fireworks_permitted',
    id: '-120',
    inProductCategories: partyWedding,
  },
];

export const amenityCatalog = new Catalog<AmenityMeta>().withItems(_itemsSource);
