/* tslint:disable:max-line-length */
import { Country } from '@src/core/domain';
import { Catalog, Currency } from '@src/core';

// TODO: replace this with the countries submodule?

const _itemsSource: Country[] = [
  { 'id': 'AS', 'description': 'American Samoa', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'AD', 'description': 'Andorra', 'currency': Currency.EUR, 'lang': 'cat' },
  { 'id': 'AM', 'description': 'Armenia', 'currency': Currency.AMD, 'lang': 'hye' },
  { 'id': 'AT', 'description': 'Austria', 'currency': Currency.EUR, 'lang': 'bar', 'native': '\u00d6sterreich' },
  { 'id': 'BE', 'description': 'Belgium', 'currency': Currency.EUR, 'lang': 'deu', 'native': 'Belgien' },
  { 'id': 'BZ', 'description': 'Belize', 'currency': Currency.BZD, 'lang': 'bjz' },
  { 'id': 'IO', 'description': 'British Indian Ocean Territory', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'VG', 'description': 'British Virgin Islands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'CA', 'description': 'Canada', 'currency': Currency.CAD, 'lang': 'eng' },
  { 'id': 'BQ', 'description': 'Caribbean Netherlands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'CN', 'description': 'China', 'currency': Currency.CNY, 'lang': 'zho' },
  { 'id': 'CY', 'description': 'Cyprus', 'currency': Currency.EUR, 'lang': 'ell' },
  { 'id': 'EC', 'description': 'Ecuador', 'currency': Currency.USD, 'lang': 'spa' },
  { 'id': 'EE', 'description': 'Estonia', 'currency': Currency.EUR, 'lang': 'est', 'native': 'Eesti' },
  { 'id': 'FI', 'description': 'Finland', 'currency': Currency.EUR, 'lang': 'fin', 'native': 'Suomi' },
  { 'id': 'FR', 'description': 'France', 'currency': Currency.EUR, 'lang': 'fra' },
  { 'id': 'GF', 'description': 'French Guiana', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'Guyane' },
  { 'id': 'TF', 'description': 'French Southern and Antarctic Lands', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'Terres australes et antarctiques fran\u00e7aises' },
  { 'id': 'DE', 'description': 'Germany', 'currency': Currency.EUR, 'lang': 'deu', 'native': 'Deutschland' },
  { 'id': 'GR', 'description': 'Greece', 'currency': Currency.EUR, 'lang': 'ell' },
  { 'id': 'GP', 'description': 'Guadeloupe', 'currency': Currency.EUR, 'lang': 'fra' },
  { 'id': 'GU', 'description': 'Guam', 'currency': Currency.USD, 'lang': 'cha' },
  { 'id': 'GG', 'description': 'Guernsey', 'currency': Currency.GBP, 'lang': 'eng' },
  { 'id': 'IN', 'description': 'India', 'currency': Currency.INR, 'lang': 'eng' },
  { 'id': 'ID', 'description': 'Indonesia', 'currency': Currency.IDR, 'lang': 'ind' },
  { 'id': 'IE', 'description': 'Ireland', 'currency': Currency.EUR, 'lang': 'eng' },
  { 'id': 'IM', 'description': 'Isle of Man', 'currency': Currency.GBP, 'lang': 'eng' },
  { 'id': 'IL', 'description': 'Israel', 'currency': Currency.ILS, 'lang': 'ara' },
  { 'id': 'IT', 'description': 'Italy', 'currency': Currency.EUR, 'lang': 'ita', 'native': 'Italia' },
  { 'id': 'JE', 'description': 'Jersey', 'currency': Currency.GBP, 'lang': 'eng' },
  { 'id': 'XK', 'description': 'Kosovo', 'currency': Currency.EUR, 'lang': 'sqi' },
  { 'id': 'LV', 'description': 'Latvia', 'currency': Currency.EUR, 'lang': 'lav', 'native': 'Latvija' },
  { 'id': 'LI', 'description': 'Liechtenstein', 'currency': Currency.CHF, 'lang': 'deu', 'native': 'Liechtenstein' },
  { 'id': 'LT', 'description': 'Lithuania', 'currency': Currency.EUR, 'lang': 'lit', 'native': 'Lietuva' },
  { 'id': 'LU', 'description': 'Luxembourg', 'currency': Currency.EUR, 'lang': 'deu', 'native': 'Luxemburg' },
  { 'id': 'MT', 'description': 'Malta', 'currency': Currency.EUR, 'lang': 'eng' },
  { 'id': 'MH', 'description': 'Marshall Islands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'MQ', 'description': 'Martinique', 'currency': Currency.EUR, 'lang': 'fra' },
  { 'id': 'YT', 'description': 'Mayotte', 'currency': Currency.EUR, 'lang': 'fra' },
  { 'id': 'FM', 'description': 'Micronesia', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'MC', 'description': 'Monaco', 'currency': Currency.EUR, 'lang': 'fra' },
  { 'id': 'ME', 'description': 'Montenegro', 'currency': Currency.EUR, 'lang': 'srp' },
  { 'id': 'NL', 'description': 'Netherlands', 'currency': Currency.EUR, 'lang': 'nld', 'native': 'Nederland' },
  { 'id': 'MP', 'description': 'Northern Mariana Islands', 'currency': Currency.USD, 'lang': 'cal' },
  { 'id': 'PK', 'description': 'Pakistan', 'currency': Currency.PKR, 'lang': 'eng' },
  { 'id': 'PW', 'description': 'Palau', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'PS', 'description': 'Palestine', 'currency': Currency.ILS, 'lang': 'ara' },
  { 'id': 'PL', 'description': 'Poland', 'currency': Currency.PLN, 'lang': 'pol', 'native': 'Polska' },
  { 'id': 'PT', 'description': 'Portugal', 'currency': Currency.EUR, 'lang': 'por' },
  { 'id': 'PR', 'description': 'Puerto Rico', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'RE', 'description': 'Réunion', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'R\u00e9union' },
  { 'id': 'BL', 'description': 'Saint Barthélemy', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'Saint-Barth\u00e9lemy' },
  { 'id': 'MF', 'description': 'Saint Martin', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'Saint-Martin' },
  { 'id': 'PM', 'description': 'Saint Pierre and Miquelon', 'currency': Currency.EUR, 'lang': 'fra', 'native': 'Saint-Pierre-et-Miquelon' },
  { 'id': 'SM', 'description': 'San Marino', 'currency': Currency.EUR, 'lang': 'ita' },
  { 'id': 'SK', 'description': 'Slovakia', 'currency': Currency.EUR, 'lang': 'slk', 'native': 'Slovensko' },
  { 'id': 'SI', 'description': 'Slovenia', 'currency': Currency.EUR, 'lang': 'slv', 'native': 'Slovenija' },
  { 'id': 'ZA', 'description': 'South Africa', 'currency': Currency.ZAR, 'lang': 'afr' },
  { 'id': 'GS', 'description': 'South Georgia', 'currency': Currency.GBP, 'lang': 'eng' },
  { 'id': 'ES', 'description': 'Spain', 'currency': Currency.EUR, 'lang': 'spa', 'native': 'Espa\u00f1a' },
  { 'id': 'SE', 'description': 'Sweden', 'currency': Currency.SEK, 'lang': 'swe', 'native': 'Sverige' },
  { 'id': 'CH', 'description': 'Switzerland', 'currency': Currency.CHF, 'lang': 'fra', 'native': 'Suisse' },
  { 'id': 'TL', 'description': 'Timor-Leste', 'currency': Currency.USD, 'lang': 'por' },
  { 'id': 'TC', 'description': 'Turks and Caicos Islands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'GB', 'description': 'United Kingdom', 'currency': Currency.GBP, 'lang': 'eng' },
  { 'id': 'US', 'description': 'United States', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'UM', 'description': 'United States Minor Outlying Islands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'VI', 'description': 'United States Virgin Islands', 'currency': Currency.USD, 'lang': 'eng' },
  { 'id': 'VA', 'description': 'Vatican City', 'currency': Currency.EUR, 'lang': 'ita', 'native': 'Vaticano' },
  { 'id': 'AX', 'description': 'Åland Islands', 'currency': Currency.EUR, 'lang': 'swe', 'native': '\u00c5land' },
];

export const countryCatalog = new Catalog<Country>().withItems(_itemsSource);
