import { Catalog, CatalogItem, Ref } from '@src/core';

type CurrencyMeta = CatalogItem<Ref> & {
  symbol: string;
};

// TODO: replace this with the currency submodule?

const _itemsSource: CurrencyMeta[] = [
  { 'id': 'AED', 'symbol': '\u062f.\u0625;', 'description': 'UAE dirham' },
  { 'id': 'AFN', 'symbol': 'Afs', 'description': 'Afghan afghani' },
  { 'id': 'ALL', 'symbol': 'L', 'description': 'Albanian lek' },
  { 'id': 'AMD', 'symbol': 'AMD', 'description': 'Armenian dram' },
  { 'id': 'ANG', 'symbol': 'NA\u0192', 'description': 'Netherlands Antillean gulden' },
  { 'id': 'AOA', 'symbol': 'Kz', 'description': 'Angolan kwanza' },
  { 'id': 'ARS', 'symbol': '$', 'description': 'Argentine peso' },
  { 'id': 'AUD', 'symbol': '$', 'description': 'Australian dollar' },
  { 'id': 'AWG', 'symbol': '\u0192', 'description': 'Aruban florin' },
  { 'id': 'AZN', 'symbol': 'AZN', 'description': 'Azerbaijani manat' },
  { 'id': 'BAM', 'symbol': 'KM', 'description': 'Bosnia and Herzegovina konvertibilna marka' },
  { 'id': 'BBD', 'symbol': 'Bds$', 'description': 'Barbadian dollar' },
  { 'id': 'BDT', 'symbol': '\u09f3', 'description': 'Bangladeshi taka' },
  { 'id': 'BGN', 'symbol': 'BGN', 'description': 'Bulgarian lev' },
  { 'id': 'BHD', 'symbol': '.\u062f.\u0628', 'description': 'Bahraini dinar' },
  { 'id': 'BIF', 'symbol': 'FBu', 'description': 'Burundi franc' },
  { 'id': 'BMD', 'symbol': 'BD$', 'description': 'Bermudian dollar' },
  { 'id': 'BND', 'symbol': 'B$', 'description': 'Brunei dollar' },
  { 'id': 'BOB', 'symbol': 'Bs.', 'description': 'Bolivian boliviano' },
  { 'id': 'BRL', 'symbol': 'R$', 'description': 'Brazilian real' },
  { 'id': 'BSD', 'symbol': 'B$', 'description': 'Bahamian dollar' },
  { 'id': 'BTN', 'symbol': 'Nu.', 'description': 'Bhutanese ngultrum' },
  { 'id': 'BWP', 'symbol': 'P', 'description': 'Botswana pula' },
  { 'id': 'BYR', 'symbol': 'Br', 'description': 'Belarusian ruble' },
  { 'id': 'BZD', 'symbol': 'BZ$', 'description': 'Belize dollar' },
  { 'id': 'CAD', 'symbol': '$', 'description': 'Canadian dollar' },
  { 'id': 'CDF', 'symbol': 'F', 'description': 'Congolese franc' },
  { 'id': 'CHF', 'symbol': 'Fr.', 'description': 'Swiss franc' },
  { 'id': 'CLP', 'symbol': '$', 'description': 'Chilean peso' },
  { 'id': 'CNY', 'symbol': '\u00a5', 'description': 'Chinese/Yuan renminbi' },
  { 'id': 'COP', 'symbol': 'Col$', 'description': 'Colombian peso' },
  { 'id': 'CRC', 'symbol': '\u20a1', 'description': 'Costa Rican colon' },
  { 'id': 'CUC', 'symbol': '$', 'description': 'Cuban peso' },
  { 'id': 'CVE', 'symbol': 'Esc', 'description': 'Cape Verdean escudo' },
  { 'id': 'CZK', 'symbol': 'K\u010d', 'description': 'Czech koruna' },
  { 'id': 'DJF', 'symbol': 'Fdj', 'description': 'Djiboutian franc' },
  { 'id': 'DKK', 'symbol': 'Kr', 'description': 'Danish krone' },
  { 'id': 'DOP', 'symbol': 'RD$', 'description': 'Dominican peso' },
  { 'id': 'DZD', 'symbol': '\u062f.\u062c', 'description': 'Algerian dinar' },
  { 'id': 'EEK', 'symbol': 'KR', 'description': 'Estonian kroon' },
  { 'id': 'EGP', 'symbol': '\u00a3', 'description': 'Egyptian pound' },
  { 'id': 'ERN', 'symbol': 'Nfa', 'description': 'Eritrean nakfa' },
  { 'id': 'ETB', 'symbol': 'Br', 'description': 'Ethiopian birr' },
  { 'id': 'EUR', 'symbol': '\u20ac', 'description': 'European Euro' },
  { 'id': 'FJD', 'symbol': 'FJ$', 'description': 'Fijian dollar' },
  { 'id': 'FKP', 'symbol': '\u00a3', 'description': 'Falkland Islands pound' },
  { 'id': 'GBP', 'symbol': '\u00a3', 'description': 'British pound' },
  { 'id': 'GEL', 'symbol': 'GEL', 'description': 'Georgian lari' },
  { 'id': 'GHS', 'symbol': 'GH\u20b5', 'description': 'Ghanaian cedi' },
  { 'id': 'GIP', 'symbol': '\u00a3', 'description': 'Gibraltar pound' },
  { 'id': 'GMD', 'symbol': 'D', 'description': 'Gambian dalasi' },
  { 'id': 'GNF', 'symbol': 'FG', 'description': 'Guinean franc' },
  { 'id': 'GQE', 'symbol': 'CFA', 'description': 'Central African CFA franc' },
  { 'id': 'GTQ', 'symbol': 'Q', 'description': 'Guatemalan quetzal' },
  { 'id': 'GYD', 'symbol': 'GY$', 'description': 'Guyanese dollar' },
  { 'id': 'HKD', 'symbol': 'HK$', 'description': 'Hong Kong dollar' },
  { 'id': 'HNL', 'symbol': 'L', 'description': 'Honduran lempira' },
  { 'id': 'HRK', 'symbol': 'kn', 'description': 'Croatian kuna' },
  { 'id': 'HTG', 'symbol': 'G', 'description': 'Haitian gourde' },
  { 'id': 'HUF', 'symbol': 'Ft', 'description': 'Hungarian forint' },
  { 'id': 'IDR', 'symbol': 'Rp', 'description': 'Indonesian rupiah' },
  { 'id': 'ILS', 'symbol': '\u20aa', 'description': 'Israeli new sheqel' },
  { 'id': 'INR', 'symbol': '\u20B9', 'description': 'Indian rupee' },
  { 'id': 'IQD', 'symbol': '\u062f.\u0639', 'description': 'Iraqi dinar' },
  { 'id': 'IRR', 'symbol': 'IRR', 'description': 'Iranian rial' },
  { 'id': 'ISK', 'symbol': 'kr', 'description': 'Icelandic kr\u00f3na' },
  { 'id': 'JMD', 'symbol': 'J$', 'description': 'Jamaican dollar' },
  { 'id': 'JOD', 'symbol': 'JOD', 'description': 'Jordanian dinar' },
  { 'id': 'JPY', 'symbol': '\u00a5', 'description': 'Japanese yen' },
  { 'id': 'KES', 'symbol': 'KSh', 'description': 'Kenyan shilling' },
  { 'id': 'KGS', 'symbol': '\u0441\u043e\u043c', 'description': 'Kyrgyzstani som' },
  { 'id': 'KHR', 'symbol': '\u17db', 'description': 'Cambodian riel' },
  { 'id': 'KMF', 'symbol': 'KMF', 'description': 'Comorian franc' },
  { 'id': 'KPW', 'symbol': 'W', 'description': 'North Korean won' },
  { 'id': 'KRW', 'symbol': 'W', 'description': 'South Korean won' },
  { 'id': 'KWD', 'symbol': 'KWD', 'description': 'Kuwaiti dinar' },
  { 'id': 'KYD', 'symbol': 'KY$', 'description': 'Cayman Islands dollar' },
  { 'id': 'KZT', 'symbol': 'T', 'description': 'Kazakhstani tenge' },
  { 'id': 'LAK', 'symbol': 'KN', 'description': 'Lao kip' },
  { 'id': 'LBP', 'symbol': '\u00a3', 'description': 'Lebanese lira' },
  { 'id': 'LKR', 'symbol': 'Rs', 'description': 'Sri Lankan rupee' },
  { 'id': 'LRD', 'symbol': 'L$', 'description': 'Liberian dollar' },
  { 'id': 'LSL', 'symbol': 'M', 'description': 'Lesotho loti' },
  { 'id': 'LTL', 'symbol': 'Lt', 'description': 'Lithuanian litas' },
  { 'id': 'LVL', 'symbol': 'Ls', 'description': 'Latvian lats' },
  { 'id': 'LYD', 'symbol': 'LD', 'description': 'Libyan dinar' },
  { 'id': 'MAD', 'symbol': 'MAD', 'description': 'Moroccan dirham' },
  { 'id': 'MDL', 'symbol': 'MDL', 'description': 'Moldovan leu' },
  { 'id': 'MGA', 'symbol': 'FMG', 'description': 'Malagasy ariary' },
  { 'id': 'MKD', 'symbol': 'MKD', 'description': 'Macedonian denar' },
  { 'id': 'MMK', 'symbol': 'K', 'description': 'Myanma kyat' },
  { 'id': 'MNT', 'symbol': '\u20ae', 'description': 'Mongolian tugrik' },
  { 'id': 'MOP', 'symbol': 'P', 'description': 'Macanese pataca' },
  { 'id': 'MRO', 'symbol': 'UM', 'description': 'Mauritanian ouguiya' },
  { 'id': 'MUR', 'symbol': 'Rs', 'description': 'Mauritian rupee' },
  { 'id': 'MVR', 'symbol': 'Rf', 'description': 'Maldivian rufiyaa' },
  { 'id': 'MWK', 'symbol': 'MK', 'description': 'Malawian kwacha' },
  { 'id': 'MXN', 'symbol': '$', 'description': 'Mexican peso' },
  { 'id': 'MYR', 'symbol': 'RM', 'description': 'Malaysian ringgit' },
  { 'id': 'MZM', 'symbol': 'MTn', 'description': 'Mozambican metical' },
  { 'id': 'NAD', 'symbol': 'N$', 'description': 'Namibian dollar' },
  { 'id': 'NGN', 'symbol': '\u20a6', 'description': 'Nigerian naira' },
  { 'id': 'NIO', 'symbol': 'C$', 'description': 'Nicaraguan c\u00f3rdoba' },
  { 'id': 'NOK', 'symbol': 'kr', 'description': 'Norwegian krone' },
  { 'id': 'NPR', 'symbol': 'NRs', 'description': 'Nepalese rupee' },
  { 'id': 'NZD', 'symbol': 'NZ$', 'description': 'New Zealand dollar' },
  { 'id': 'OMR', 'symbol': 'OMR', 'description': 'Omani rial' },
  { 'id': 'PAB', 'symbol': 'B./', 'description': 'Panamanian balboa' },
  { 'id': 'PEN', 'symbol': 'S/.', 'description': 'Peruvian nuevo sol' },
  { 'id': 'PGK', 'symbol': 'K', 'description': 'Papua New Guinean kina' },
  { 'id': 'PHP', 'symbol': '\u20b1', 'description': 'Philippine peso' },
  { 'id': 'PKR', 'symbol': 'Rs.', 'description': 'Pakistani rupee' },
  { 'id': 'PLN', 'symbol': 'z\u0142', 'description': 'Polish zloty' },
  { 'id': 'PYG', 'symbol': '\u20b2', 'description': 'Paraguayan guarani' },
  { 'id': 'QAR', 'symbol': 'QR', 'description': 'Qatari riyal' },
  { 'id': 'RON', 'symbol': 'L', 'description': 'Romanian leu' },
  { 'id': 'RSD', 'symbol': 'din.', 'description': 'Serbian dinar' },
  { 'id': 'RUB', 'symbol': 'R', 'description': 'Russian ruble' },
  { 'id': 'SAR', 'symbol': 'SR', 'description': 'Saudi riyal' },
  { 'id': 'SBD', 'symbol': 'SI$', 'description': 'Solomon Islands dollar' },
  { 'id': 'SCR', 'symbol': 'SR', 'description': 'Seychellois rupee' },
  { 'id': 'SDG', 'symbol': 'SDG', 'description': 'Sudanese pound' },
  { 'id': 'SEK', 'symbol': 'kr', 'description': 'Swedish krona' },
  { 'id': 'SGD', 'symbol': 'S$', 'description': 'Singapore dollar' },
  { 'id': 'SHP', 'symbol': '\u00a3', 'description': 'Saint Helena pound' },
  { 'id': 'SLL', 'symbol': 'Le', 'description': 'Sierra Leonean leone' },
  { 'id': 'SOS', 'symbol': 'Sh.', 'description': 'Somali shilling' },
  { 'id': 'SRD', 'symbol': '$', 'description': 'Surinamese dollar' },
  { 'id': 'SYP', 'symbol': 'LS', 'description': 'Syrian pound' },
  { 'id': 'SZL', 'symbol': 'E', 'description': 'Swazi lilangeni' },
  { 'id': 'THB', 'symbol': '\u0e3f', 'description': 'Thai baht' },
  { 'id': 'TJS', 'symbol': 'TJS', 'description': 'Tajikistani somoni' },
  { 'id': 'TMT', 'symbol': 'm', 'description': 'Turkmen manat' },
  { 'id': 'TND', 'symbol': 'DT', 'description': 'Tunisian dinar' },
  { 'id': 'TRY', 'symbol': 'TRY', 'description': 'Turkish new lira' },
  { 'id': 'TTD', 'symbol': 'TT$', 'description': 'Trinidad and Tobago dollar' },
  { 'id': 'TWD', 'symbol': 'NT$', 'description': 'New Taiwan dollar' },
  { 'id': 'TZS', 'symbol': 'TZS', 'description': 'Tanzanian shilling' },
  { 'id': 'UAH', 'symbol': 'UAH', 'description': 'Ukrainian hryvnia' },
  { 'id': 'UGX', 'symbol': 'USh', 'description': 'Ugandan shilling' },
  { 'id': 'USD', 'symbol': '$', 'description': 'United States dollar' },
  { 'id': 'UYU', 'symbol': '$U', 'description': 'Uruguayan peso' },
  { 'id': 'UZS', 'symbol': 'UZS', 'description': 'Uzbekistani som' },
  { 'id': 'VEB', 'symbol': 'Bs', 'description': 'Venezuelan bolivar' },
  { 'id': 'VND', 'symbol': '\u20ab', 'description': 'Vietnamese dong' },
  { 'id': 'VUV', 'symbol': 'VT', 'description': 'Vanuatu vatu' },
  { 'id': 'WST', 'symbol': 'WS$', 'description': 'Samoan tala' },
  { 'id': 'XAF', 'symbol': 'CFA', 'description': 'Central African CFA franc' },
  { 'id': 'XCD', 'symbol': 'EC$', 'description': 'East Caribbean dollar' },
  { 'id': 'XDR', 'symbol': 'SDR', 'description': 'Special Drawing Rights' },
  { 'id': 'XOF', 'symbol': 'CFA', 'description': 'West African CFA franc' },
  { 'id': 'XPF', 'symbol': 'F', 'description': 'CFP franc' },
  { 'id': 'YER', 'symbol': 'YER', 'description': 'Yemeni rial' },
  { 'id': 'ZAR', 'symbol': 'R', 'description': 'South African rand' },
  { 'id': 'ZMK', 'symbol': 'ZK', 'description': 'Zambian kwacha' },
  { 'id': 'ZWR', 'symbol': 'Z$', 'description': 'Zimbabwean dollar' },
];

export const currencyCatalog = new Catalog<CurrencyMeta>().withItems(_itemsSource);
