import { ConfigurationKind, ProductCategory, SpaceKind, SpaceKindMeta } from '@src/core/domain';
import { Catalog } from '@src/core';

const configOrderDefault: ConfigurationKind[] = [
  ConfigurationKind.SEATED,
  ConfigurationKind.RECEPTION,
  ConfigurationKind.BOARDROOM,
  ConfigurationKind.CLASSROOM,
  ConfigurationKind.BANQUET,
  ConfigurationKind.THEATRE,
  ConfigurationKind.U_SHAPED,
  ConfigurationKind.CABARET,
];

const configOrderMeeting: ConfigurationKind[] = [
  ConfigurationKind.BOARDROOM,
  ConfigurationKind.CLASSROOM,
  ConfigurationKind.BANQUET,
  ConfigurationKind.THEATRE,
  ConfigurationKind.U_SHAPED,
  ConfigurationKind.CABARET,
  ConfigurationKind.RECEPTION,
];

const _itemsSource: SpaceKindMeta[] = [
  {
    arrangement: {
      configurationKinds: configOrderMeeting,
      showExpandAfter: null,
    },
    assetType: 'SPACE',
    category: ProductCategory.MEETING,
    description: 'common.meeting',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    icon: 'Meeting',
    id: SpaceKind.MEETING,
    orderIndex: 0,
    priceRequired: true,
  },
  {
    assetType: 'TABLE',
    category: ProductCategory.OFFICE,
    description: 'common.office_type_hot_desk',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    iconUrl: '/_express/images/space_types/hot_desk.jpg',
    id: SpaceKind.OFFICE_HOTDESK,
    orderIndex: 1,
    priceRequired: true,
    stock: {
      title: 'common.desks_how_many_available',
      label: 'common.desks_no_of_available',
      unit: 'listing.desks_count',
    },
  },
  {
    assetType: 'TABLE',
    category: ProductCategory.OFFICE,
    description: 'common.office_type_dedicated_desk',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    iconUrl: '/_express/images/space_types/dedicated_desk.jpg',
    id: SpaceKind.OFFICE_DEDICATEDDESK,
    orderIndex: 2,
    priceRequired: true,
    stock: {
      title: 'common.desks_how_many_available',
      label: 'common.desks_no_of_available',
      unit: 'listing.desks_count',
    },
  },
  {
    assetType: 'SPACE',
    category: ProductCategory.OFFICE,
    description: 'common.office_type_private_office',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    iconUrl: '/_express/images/space_types/private_office.jpg',
    id: SpaceKind.OFFICE_PRIVATE,
    orderIndex: 3,
    priceRequired: true,
    size: {
      area: {
        label: 'common.size',
      },
      capacity: {
        label: 'listing.capacity',
        unit: 'listing.guests_count',
      },
      title: 'listing.office_space_size',
    },
  },
  // {
  //   assetType: 'TABLE',
  //   category: ProductCategory.PARTY,
  //   description: 'common.book_table',
  //   disabled: false,
  //   enablePictures: true,
  //   enablePrices: false,
  //   icon: 'Table',
  //   id: SpaceKind.PARTY_TABLE,
  //   maxPerVenue: 1,
  //   orderIndex: 4,
  //   priceRequired: false,
  //   stock: {
  //     title: 'listing.capacity',
  //     label: 'listing.space_capacity_table',
  //     unit: 'listing.guests_count',
  //   },
  // },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'SPACE',
    category: ProductCategory.PARTY,
    description: 'common.private_hire_space',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    icon: 'Party',
    id: SpaceKind.PARTY_SPACE,
    orderIndex: 5,
    priceRequired: true,
  },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'VENUE',
    category: ProductCategory.PARTY,
    description: 'common.private_hire_entire_venue',
    disabled: false,
    enablePictures: false,
    enablePrices: true,
    icon: 'Venue',
    id: SpaceKind.PARTY_VENUE,
    maxPerVenue: 1,
    orderIndex: 6,
    priceRequired: true,
  },
  // {
  //   assetType: 'TABLE',
  //   category: ProductCategory.DINING,
  //   description: 'common.book_table',
  //   disabled: false,
  //   enablePictures: true,
  //   enablePrices: false,
  //   icon: 'Table',
  //   id: SpaceKind.DINING_TABLE,
  //   maxPerVenue: 1,
  //   orderIndex: 7,
  //   priceRequired: false,
  //   stock: {
  //     title: 'listing.capacity',
  //     label: 'listing.space_capacity_table',
  //     unit: 'listing.guests_count',
  //   },
  // },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'SPACE',
    category: ProductCategory.DINING,
    description: 'common.private_dining_space',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    icon: 'Dining',
    id: SpaceKind.DINING_SPACE,
    orderIndex: 8,
    priceRequired: true,
  },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'VENUE',
    category: ProductCategory.DINING,
    description: 'common.private_hire_entire_venue',
    disabled: false,
    enablePictures: false,
    enablePrices: true,
    icon: 'Venue',
    id: SpaceKind.DINING_VENUE,
    maxPerVenue: 1,
    orderIndex: 9,
    priceRequired: true,
  },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'SPACE',
    category: ProductCategory.WEDDING,
    description: 'common.private_hire_space',
    disabled: false,
    enablePictures: true,
    enablePrices: true,
    icon: 'Wedding',
    id: SpaceKind.WEDDING_SPACE,
    orderIndex: 10,
    priceRequired: true,
  },
  {
    arrangement: {
      configurationKinds: configOrderDefault,
      showExpandAfter: 2,
    },
    assetType: 'VENUE',
    category: ProductCategory.WEDDING,
    description: 'common.private_hire_entire_venue',
    disabled: false,
    enablePictures: false,
    enablePrices: true,
    icon: 'Venue',
    id: SpaceKind.WEDDING_VENUE,
    maxPerVenue: 1,
    orderIndex: 11,
    priceRequired: true,
  },
];

export const spaceKindCatalog = new Catalog<SpaceKindMeta>().withItems(_itemsSource);
