import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  checkedBackground: {
    position: 'absolute',
    left: '-1px',
    top: '-1px',
    bottom: '-1px',
    right: '-1px',
    backgroundColor: '#00c6ff',
    opacity: 0,
    display: 'inherit',
    borderRadius: '32px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#00c6ff',
    transitionProperty: 'opacity',
    transitionDuration: '250ms',
    transitionTimingFunction: 'ease-in-out',
  },
  checkedBackground_on: {
    opacity: 1,
  },
  checkmarkCover: {
    position: 'absolute',
    top: '10px',
    left: '5px',
    right: '5px',
    bottom: '10px',
    backgroundColor: '#ffffff',
    transform: 'scaleX(1)',
    transitionDelay: '0px',
    transitionDuration: '0px',
    transformOrigin: 'right center',
  },
  checkmarkCover_on: {
    transform: 'scaleX(0)',
    transitionProperty: '-ms-transform, -webkit-transform, transform',
    transitionDelay: '125ms',
    transitionDuration: '250ms',
    transformOrigin: 'right center',
    transitionTimingFunction: 'ease-in-out',
  },
  strokeIcon: {
    display: 'block',
    height: '30px',
    width: '30px',
    overflow: 'visible',
  },
  icon: {
    strokeWidth: 3,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    fill: 'none',
    stroke: 'currentColor',
  },
  iconContainer: {
    position: 'absolute',
    top: '0px',
    left: '0px',
    right: '0px',
    bottom: '0px',
  },
  slider: {
    width: '32px',
    height: '32px',
    backgroundColor: '#ffffff',
    borderRadius: '50%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#ebebeb',
    color: '#484848',
    display: 'block',
    transitionProperty: '-ms-transform, -webkit-transform, transform',
    transitionDuration: '250ms',
    transitionTimingFunction: 'ease-in-out',
    overflow: 'hidden',
    position: 'absolute',
    top: '-1px',
    left: '-1px',
    transform: 'translate3d(0, 0, 0)',
  },
  sliderChecked: {
    transform: 'translate3d(16px, 0, 0)',
    borderColor: '#00c6ff',
    color: '#00c6ff',
  },
  times: {
    transform: 'rotate(45deg)',
    transitionDelay: '62.5ms',
    transitionProperty: '-ms-transform, -webkit-transform, transform',
  },
  times_on: {
    transform: 'rotate(0)',
  },
  timesScale: {
    transform: 'scale(0, 0)',
    transitionProperty: '-ms-transform, -webkit-transform, transform',
    transitionDelay: '0px',
    transitionDuration: '62.5ms',
  },
  timesScale_on: {
    transform: 'scale(1, 1)',
  },
  uncheckedBackground: {
    verticalAlign: 'middle',
    appearance: 'none',
    height: '32px',
    width: '48px',
    backgroundColor: '#f2f2f2',
    borderRadius: '32px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#ebebeb',
    margin: 'auto',
    position: 'relative',
    display: 'inline-block',
    cursor: 'pointer',
    outline: 'none',
    minWidth: '1px',
  },
});
