<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.graphql.CalculatedAssetsArgs</code>
 */
class CalculatedAssetsArgs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .zipcube.Id humanRefs = 1;</code>
     */
    private $humanRefs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id[]|\Google\Protobuf\Internal\RepeatedField $humanRefs
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Gql::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Id humanRefs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHumanRefs()
    {
        return $this->humanRefs;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Id humanRefs = 1;</code>
     * @param \App\Types\Id[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHumanRefs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\Id::class);
        $this->humanRefs = $arr;

        return $this;
    }

}