<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.graphql.ListingsAsset</code>
 */
class ListingsAsset extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>.zipcube.Location location = 4;</code>
     */
    private $location = null;
    /**
     * Generated from protobuf field <code>.zipcube.Currency currency = 5;</code>
     */
    private $currency = 0;
    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 6;</code>
     */
    private $context = null;
    /**
     * Generated from protobuf field <code>.zipcube.Area area = 7;</code>
     */
    private $area = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.Usage usages = 8;</code>
     */
    private $usages;
    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageEdge images = 9;</code>
     */
    private $images;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $id
     *     @type string $name
     *     @type string $description
     *     @type \App\Types\Location $location
     *     @type int $currency
     *     @type \App\Types\ProductContext $context
     *     @type \App\Types\Area $area
     *     @type \App\Types\Usage[]|\Google\Protobuf\Internal\RepeatedField $usages
     *     @type \App\Types\ImageEdge[]|\Google\Protobuf\Internal\RepeatedField $images
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Gql::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @return \App\Types\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Location location = 4;</code>
     * @return \App\Types\Location
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Location location = 4;</code>
     * @param \App\Types\Location $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Location::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Currency currency = 5;</code>
     * @return int
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Currency currency = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \App\Types\Currency::class);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 6;</code>
     * @return \App\Types\ProductContext
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.zipcube.ProductContext context = 6;</code>
     * @param \App\Types\ProductContext $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \App\Types\ProductContext::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Area area = 7;</code>
     * @return \App\Types\Area
     */
    public function getArea()
    {
        return $this->area;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Area area = 7;</code>
     * @param \App\Types\Area $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Area::class);
        $this->area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Usage usages = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUsages()
    {
        return $this->usages;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.Usage usages = 8;</code>
     * @param \App\Types\Usage[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUsages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\Usage::class);
        $this->usages = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageEdge images = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.ImageEdge images = 9;</code>
     * @param \App\Types\ImageEdge[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\ImageEdge::class);
        $this->images = $arr;

        return $this;
    }

}

