<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.graphql.ListingsVenue</code>
 */
class ListingsVenue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.graphql.ListingsAsset asset = 1;</code>
     */
    private $asset = null;
    /**
     * Generated from protobuf field <code>.zipcube.VenueDetails details = 2;</code>
     */
    private $details = null;
    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.ListingsSpace spaces = 3;</code>
     */
    private $spaces;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\GQL\ListingsAsset $asset
     *     @type \App\Types\VenueDetails $details
     *     @type \App\Types\GQL\ListingsSpace[]|\Google\Protobuf\Internal\RepeatedField $spaces
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Gql::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.graphql.ListingsAsset asset = 1;</code>
     * @return \App\Types\GQL\ListingsAsset
     */
    public function getAsset()
    {
        return $this->asset;
    }

    /**
     * Generated from protobuf field <code>.zipcube.graphql.ListingsAsset asset = 1;</code>
     * @param \App\Types\GQL\ListingsAsset $var
     * @return $this
     */
    public function setAsset($var)
    {
        GPBUtil::checkMessage($var, \App\Types\GQL\ListingsAsset::class);
        $this->asset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.VenueDetails details = 2;</code>
     * @return \App\Types\VenueDetails
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Generated from protobuf field <code>.zipcube.VenueDetails details = 2;</code>
     * @param \App\Types\VenueDetails $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkMessage($var, \App\Types\VenueDetails::class);
        $this->details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.ListingsSpace spaces = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpaces()
    {
        return $this->spaces;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.ListingsSpace spaces = 3;</code>
     * @param \App\Types\GQL\ListingsSpace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpaces($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\GQL\ListingsSpace::class);
        $this->spaces = $arr;

        return $this;
    }

}

