<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.graphql.MutationResult</code>
 */
class MutationResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.Problem problems = 1;</code>
     */
    private $problems;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\GQL\Problem[]|\Google\Protobuf\Internal\RepeatedField $problems
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Gql::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.Problem problems = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProblems()
    {
        return $this->problems;
    }

    /**
     * Generated from protobuf field <code>repeated .zipcube.graphql.Problem problems = 1;</code>
     * @param \App\Types\GQL\Problem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProblems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Types\GQL\Problem::class);
        $this->problems = $arr;

        return $this;
    }

}

