<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>zipcube.graphql.PatchAddressInput</code>
 */
class PatchAddressInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     */
    private $id = null;
    /**
     * Generated from protobuf field <code>.zipcube.Address address = 2;</code>
     */
    private $address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Types\Id $id
     *     @type \App\Types\Address $address
     * }
     */
    public function __construct($data = NULL) {
        \ProtobufMeta\Gql::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @return \App\Types\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Id id = 1;</code>
     * @param \App\Types\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Id::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Address address = 2;</code>
     * @return \App\Types\Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.zipcube.Address address = 2;</code>
     * @param \App\Types\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \App\Types\Address::class);
        $this->address = $var;

        return $this;
    }

}

