<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/gql.proto

namespace App\Types\GQL;

use UnexpectedValueException;

/**
 * Protobuf type <code>zipcube.graphql.ProblemType</code>
 */
class ProblemType
{
    /**
     * Generated from protobuf enum <code>NOPROBLEM = 0;</code>
     */
    const NOPROBLEM = 0;
    /**
     * Generated from protobuf enum <code>AUTHENTICATION = 1;</code>
     */
    const AUTHENTICATION = 1;
    /**
     * Generated from protobuf enum <code>AUTHORIZATION = 2;</code>
     */
    const AUTHORIZATION = 2;
    /**
     * Generated from protobuf enum <code>VALIDATION = 3;</code>
     */
    const VALIDATION = 3;

    private static $valueToName = [
        self::NOPROBLEM => 'NOPROBLEM',
        self::AUTHENTICATION => 'AUTHENTICATION',
        self::AUTHORIZATION => 'AUTHORIZATION',
        self::VALIDATION => 'VALIDATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

