version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV
      - restore_cache: 
          key: yarn-cache-{{ checksum "package.json" }}
      - restore_cache: 
          key: node-modules-cache-{{ checksum "package.json" }}
      - run:
          name: Setup yarn
          command: yarn
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-modules-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn run ci-build
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: circleci

  # deployment:
  #     - run: echo 162.13.9.51 stage | sudo tee -a /etc/hosts
  #     - run: echo 162.13.82.159 live | sudo tee -a /etc/hosts
  #   production:
  #     branch: master
  #     commands:
  #       - sftp -b ~/zipcube/ci_scripts/sftp_deploy ci@live
  #       - ssh ci@live "bash --login -c 'cd zip; git pull origin master'"
  #
  #   staging:
  #     branch: develop
  #     commands:
  #       - sftp -vvv -b ~/zipcube/ci_scripts/sftp_deploy ci@stage
  #       - ssh -v ci@stage "bash --login -c 'cd zip; git pull origin develop'"
