import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  guestPanel: {
    position: 'relative',
    top: '-39px',
  },
  guestPanelDropdown: {
    position: 'absolute',
    top: '40px',
    left: '0px',
    zIndex: 10,
    background: '#ffffff',
    border: '1px solid rgba(0, 0, 0, 0.2)',
    borderRadius: '4px',
    boxShadow: '0px 14px 36px 2px rgba(0, 0, 0, 0.15)',
    overflowY: 'auto',
    visibility: 'visible',
    whiteSpace: 'normal',
    borderTopLeftRadius: '0px',
    borderTopRightRadius: '0px',
    width: '200px',
    maxHeight: '30vh',
  },
  guestPanelDropdownItems: {
    padding: '0px',
    margin: '0px',
  },
  guestPanelButton: {
    fontFamily: 'Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif',
    fontSize: '19px',
    lineHeight: '24px',
    letterSpacing: '0.2px',
    paddingTop: '8px',
    paddingBottom: '12px',
    color: '#484848',
    paddingLeft: '8px',
    paddingRight: '8px',
    background: '#ffffff',
    border: '0px none',
    borderRadius: '4px',
    cursor: 'pointer',
    display: 'inline',
    textAlign: 'left',
    position: 'relative',
    width: '100%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    outline: 'none',
  },
  guestPanelDropdownIcon: {
    color: '#767676',
    display: 'inline-block',
    verticalAlign: 'middle',
  },
  guestPanelPlaceholder: {
    color: '#767676',
    marginLeft: '8px',
    verticalAlign: 'middle',
  },
  guestPanelDropdownChevron: {
    color: '#484848',
    display: 'inline-block',
    verticalAlign: 'middle',
    marginLeft: '16px',
  },
  guestPanelDropdownChevronWrapper: {
    WebkitTransitionProperty: '-ms-transform, -webkit-transform, transform',
    MozTransitionProperty: 'transform',
    transitionProperty: '-ms-transform, -webkit-transform, transform',
    WebkitTransitionDuration: '250ms',
    transitionDuration: '250ms',
    WebkitTransitionTimingFunction: 'ease-in-out',
    transitionTimingFunction: 'ease-in-out',
    transform: 'rotate(0deg)',
  },
  guestPanelDropdownItem: {
    cursor: 'pointer',
    display: 'table',
    listStyleType: 'none',
    padding: '5px 12px',
    width: '100%',
  },
  guestPanelDropdownItemTextContainer: {
    width: '100%',
    pointerEvents: 'none',
  },
  guestPanelDropdownItemFiltersText: {
    fontWeight: 300,
    color: '#484848',
    margin: '0px',
    overflowWrap: 'break-word',
    fontSize: '15px',
    lineHeight: '18px',
    letterSpacing: '0.2px',
    paddingTop: '0px',
    paddingBottom: '0px',
    pointerEvents: 'none',
  },
});
