import { StyleSheet } from 'aphrodite/no-important';
import { specs } from '@src/core/ux';

export default StyleSheet.create({
  container: {
    position: 'relative',
    display: 'inline-block',
    verticalAlign: 'middle',
    minWidth: '100%',
    borderBottom: '1px solid #ebebeb',
  },
  text: {
    fontSize: '14px',
    lineHeight: '1.43',
  },
  buttonSelected: {
    fontSize: '16px',
    lineHeight: '22px',
    letterSpacing: 'normal',
    fontFamily: specs.fontFamily,
    textTransform: undefined,
    fontWeight: 600,
    backgroundColor: 'transparent',
    borderRadius: '0px',
    borderWidth: '0px',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    bottom: '-1px',
    cursor: 'pointer',
    display: 'block',
    marginRight: '32px',
    paddingLeft: '0px',
    paddingRight: '0px',
    paddingTop: '24px',
    paddingBottom: '24px',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    borderBottomColor: specs.primary,
    color: specs.primary,
    WebkitTransitionProperty: 'color',
    MozTransitionProperty: 'color',
    TransitionProperty: 'color',
    WebkitTransitionDuration: '300ms',
    TransitionDuration: '300ms',
    WebkitTransitionTimingFunction: 'ease-out',
    TransitionTimingFunction: 'ease-out',
    outline: 'none',
    ':active': {
      outline: '0px',
    },
    '::-moz-focus-inner': {
      border: '0px',
      padding: '0px',
      margin: '0px',
    },
    ':focus::-moz-focus-inner': {
      border: '1px dotted #000000',
    },
    ':-moz-focusring': {
      outlineColor: '#000000',
    },
  },
  buttonNormal: {
    fontSize: '16px',
    lineHeight: '22px',
    letterSpacing: 'normal',
    fontFamily: specs.fontFamily,
    textTransform: undefined,
    color: specs.textColor,
    fontWeight: 600,
    backgroundColor: 'transparent',
    borderRadius: '0px',
    borderWidth: '0px',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    bottom: '-1px',
    cursor: 'pointer',
    display: 'block',
    marginRight: '32px',
    paddingLeft: '0px',
    paddingRight: '0px',
    paddingTop: '24px',
    paddingBottom: '24px',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    outline: 'none',
    ':active': {
      outline: '0px',
    },
    '::-moz-focus-inner': {
      border: '0px',
      padding: '0px',
      margin: '0px',
    },
    ':focus::-moz-focus-inner': {
      border: '1px dotted #000000',
    },
    ':-moz-focusring': {
      outlineColor: '#000000',
    },
  },
  buttonContainer: {
    display: 'inline-block',
  },
});
