const suggestions = [
    'Auction',
    'Ballroom',
    'Banquet Hall',
    'Charity Event',
    'Corporate Event',
    'Corporate Party',
    'Exhibit',
    'Fashion Event',
    'Fashion Show',
    'Fundraising Event',
    'Gala',
    'Gallery',
    'Launch Event',
    'Party Hall',
    'Product Demo',
    'Product Release',
    'Product Showcase',
    'Rooftop',
    'Breakfast',
    'Brunch',
    'Cooking Class',
    'Dinner',
    'Kitchen',
    'Luncheon',
    'Rehearsal Dinner',
    'TV Series Shoot',
    'Dance Shoot',
    'Documentary Shoot',
    'Filming',
    'Film Shoot',
    'Film Studio',
    'Production',
    'Fitness Video',
    'Green Screen',
    'Filmed Interview',
    'Kickstarter Video',
    'Music Video',
    'Promotional Video',
    'Recording Studio',
    'Sound Stage',
    'Video Shoot',
    'Video Studio',
    'Web Series Shoot',
    'Workout Video',
    'Dance Class',
    'Dance Studio',
    'Fitness Class',
    'Fitness Studio',
    'Pilates Class',
    'Workout Class',
    'Yoga Class',
    'Yoga Studio',
    'Audition',
    'Boardroom',
    'Brainstorm',
    'Casting',
    'Conference Room',
    'Corporate Meeting',
    'Creative Meeting',
    'Discussion',
    'Group Work',
    'Interview',
    'Meeting',
    'Off-Site',
    'Planning Session',
    'Sales Meeting',
    'Therapy',
    'Work Session',
    'Career Expo',
    'Funeral',
    'Job Fair',
    'Loft',
    'Meetup',
    'Memorial',
    'Mixer',
    'Networking',
    'Baby Shower',
    'Bachelor Party',
    'Beer And Wine Tasting',
    'Birthday Party',
    'Bridal Shower',
    'Celebration',
    'Cocktail Party',
    'Dance Party',
    'Engagement Party',
    'Event',
    'Food Tasting',
    'Function',
    'Gathering',
    'Graduation Party',
    'Happy Hour',
    'Holiday Party',
    'Marriage Proposal',
    'Outdoor Event',
    'Outdoor Party',
    'Party',
    'Private Party',
    'Reception',
    'Reunion',
    'Wedding Reception',
    'Wedding Shower',
    'Auditorium',
    'Concert',
    'Performance',
    'Poetry',
    'Recital',
    'Screening',
    'Theater',
    'Apparel Shoot',
    'Clothing Shoot',
    'Commercial Photoshoot',
    'Fashion Shoot',
    'Head Shot',
    'Photo Shoot',
    'Photo Studio',
    'Portrait Photoshoot',
    'Product Shoot',
    'Promotional Photoshoot',
    'Pop-Up',
    'Retail',
    'Storefront',
    'Retreat',
    'Team Building',
    'Bar And Bat Mitzvah',
    'Graduation Ceremony',
    'Quinceanera',
    'Sweet 16',
    'Wedding',
    'Church',
    'Class',
    'Classroom',
    'Coaching',
    'Collaboration',
    'Convention',
    'Focus Group',
    'Forum',
    'Hackathon',
    'Improv',
    'Lecture',
    'Orientation',
    'Presentation',
    'Seminar',
    'Speaker Event',
    'Speaker Panel',
    'Summit',
    'Training',
    'Workshop'
];

export default suggestions;
