FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y apache2
RUN apt-get install -y language-pack-en-base
RUN apt-get install -y software-properties-common
RUN apt-get install -y python-software-properties
RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN apt-get -y install php5.6 php5.6-mcrypt php5.6-mbstring php5.6-curl php5.6-cli php5.6-mysql php5.6-gd php5.6-intl php5.6-xsl php5.6-zip

RUN a2enmod rewrite
RUN a2enmod headers
RUN a2enmod php5.6

COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html

ADD ./container_environment/apache2.conf /etc/apache2/apache2.conf
ADD ./container_environment/mpm_prefork.conf /etc/apache2/mods-available/mpm_prefork.conf
ADD ./container_environment/000-default.conf /etc/apache2/sites-available/000-default.conf

ADD ./container_environment/bootstrap.sh /bootstrap.sh
RUN chmod 755 /bootstrap.sh

EXPOSE 80

CMD ["/bootstrap.sh"]
