import { StyleSheet } from 'aphrodite/no-important';

export default StyleSheet.create({
  wrapper: {
    boxSizing: 'border-box',
    left: '0px',
    maxWidth: 'none',
    verticalAlign: 'middle',
    width: '100%',
    minWidth: '100%',
    height: '82px',
    position: 'absolute',
    backgroundColor: '#ffffff',
    zIndex: 5,
    top: '64px',
    '@media (min-width: 744px)': {
      top: '81px',
    },
  },
  sticky: {
    position: 'fixed',
    top: '0px',
    '@media (min-width: 744px)': {
      top: '0px',
    },
  },
  container: {
    backgroundColor: 'transparent',
    maxWidth: 'none',
    margin: '0px auto',
    position: 'relative',
    overflowY: 'hidden',
  },
  listContainer: {
    display: 'table',
    width: '100%',
    borderSpacing: '0px',
    overflowX: 'scroll',
    overflowY: 'auto',
  },
  list: {
    whiteSpace: 'nowrap',
    boxSizing: 'border-box',
    display: 'inline-block',
    backgroundColor: '#ffffff',
  },
  buttonWrapper: {
    display: 'inline-block',
    lineHeight: '64px',
    verticalAlign: 'middle',
    position: 'fixed',
    bottom: '0px',
    left: '0px',
    width: '100%',
    backgroundColor: '#ffffff',
    borderTop: '1px solid #ebebeb',
    zIndex: -1,
    '@media (min-width: 1128px)': {
      position: 'static',
      minWidth: '400px',
      whiteSpace: 'nowrap',
      backgroundColor: 'transparent',
      borderTop: 'medium none',
      height: '64px',
      lineHeight: '62px',
    },
  },
  buttonContainer: {
    letterSpacing: 'normal',
    width: '100%',
    display: 'block',
    lineHeight: '64px',
    textAlign: 'right',
    '@media (min-width: 1128px)': {
      lineHeight: 'inherit',
    },
  },
  inner: {
    height: '100%',
    textAlign: 'right',
    whiteSpace: 'nowrap',
    display: 'inline-block',
    float: 'none',
    verticalAlign: 'baseline',
    position: 'static',
    top: 'auto',
    right: 'auto',
  },
  button: {
    width: 'auto',
    fontSize: '14px',
    letterSpacing: 'normal',
    padding: '6px 15px',
    fontWeight: 600,
    minWidth: '48.541px',
    boxShadow: 'none',
  },
  span: {
    fontSize: '14px',
    letterSpacing: 'normal',
  },
});
