<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zipcube/generics.proto

namespace ProtobufMeta;

class Generics
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83010a167a6970637562652f67656e65726963732e70726f746f12077a" .
            "69706375626522130a024964120d0a0576616c756518012001280922260a" .
            "03434964121f0a0a636f6c6c656374696f6e18012003280b320b2e7a6970" .
            "637562652e4964421bca02094170705c5479706573e2020c50726f746f62" .
            "75664d657461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

